In [4]:
import pandas as pd
import numpy as np
import random
from datetime import datetime, timedelta
from pathlib import Path

In [5]:
print("Healthcare analytics environment is ready!")

Healthcare analytics environment is ready!

In [6]:
random.seed(42)
np.random.seed(42)

print("Random seed set.")

Random seed set.

In [ ]:
from pathlib import Path


print("Current working directory:")
print(Path.cwd())

Current working directory:
c:\New folder\Hands on Projects\healthcare-operations-population-health-analytics\python

In [9]:
RAW_DATA_PATH = Path("../data/raw")

In [10]:
RAW_DATA_PATH.mkdir(parents=True, exist_ok=True)

print("Raw data path:", RAW_DATA_PATH.resolve())

Raw data path: C:\New folder\Hands on Projects\healthcare-operations-population-health-analytics\data\raw

In [14]:
department_records = [
    # RiverCare Central Hospital
    ("DEP001", "Emergency Department", "RiverCare Central Hospital", "Emergency", "Richmond", "VA"),
    ("DEP002", "General Medicine", "RiverCare Central Hospital", "Inpatient", "Richmond", "VA"),
    ("DEP003", "Cardiology", "RiverCare Central Hospital", "Specialty", "Richmond", "VA"),
    ("DEP004", "Neurology", "RiverCare Central Hospital", "Specialty", "Richmond", "VA"),
    ("DEP005", "Orthopedics", "RiverCare Central Hospital", "Specialty", "Richmond", "VA"),
    ("DEP006", "Oncology", "RiverCare Central Hospital", "Specialty", "Richmond", "VA"),

    # RiverCare North Hospital
    ("DEP007", "Emergency Department", "RiverCare North Hospital", "Emergency", "Fredericksburg", "VA"),
    ("DEP008", "General Medicine", "RiverCare North Hospital", "Inpatient", "Fredericksburg", "VA"),
    ("DEP009", "Cardiology", "RiverCare North Hospital", "Specialty", "Fredericksburg", "VA"),
    ("DEP010", "Pediatrics", "RiverCare North Hospital", "Specialty", "Fredericksburg", "VA"),
    ("DEP011", "Pulmonology", "RiverCare North Hospital", "Specialty", "Fredericksburg", "VA"),

    # RiverCare West Medical Center
    ("DEP012", "Emergency Department", "RiverCare West Medical Center", "Emergency", "Charlottesville", "VA"),
    ("DEP013", "General Medicine", "RiverCare West Medical Center", "Inpatient", "Charlottesville", "VA"),
    ("DEP014", "Cardiology", "RiverCare West Medical Center", "Specialty", "Charlottesville", "VA"),
    ("DEP015", "Gastroenterology", "RiverCare West Medical Center", "Specialty", "Charlottesville", "VA"),
    ("DEP016", "Endocrinology", "RiverCare West Medical Center", "Specialty", "Charlottesville", "VA"),

    # RiverCare Downtown Clinic
    ("DEP017", "Primary Care", "RiverCare Downtown Clinic", "Primary Care", "Richmond", "VA"),
    ("DEP018", "Behavioral Health", "RiverCare Downtown Clinic", "Behavioral Health", "Richmond", "VA"),
    ("DEP019", "Endocrinology", "RiverCare Downtown Clinic", "Outpatient", "Richmond", "VA"),
    ("DEP020", "Cardiology", "RiverCare Downtown Clinic", "Outpatient", "Richmond", "VA"),

    # RiverCare Community Clinic
    ("DEP021", "Primary Care", "RiverCare Community Clinic", "Primary Care", "Petersburg", "VA"),
    ("DEP022", "Pediatrics", "RiverCare Community Clinic", "Outpatient", "Petersburg", "VA"),
    ("DEP023", "Behavioral Health", "RiverCare Community Clinic", "Behavioral Health", "Petersburg", "VA"),
    ("DEP024", "Pulmonology", "RiverCare Community Clinic", "Outpatient", "Petersburg", "VA"),
    ("DEP025", "Orthopedics", "RiverCare Community Clinic", "Outpatient", "Petersburg", "VA"),
]

In [15]:
departments_df = pd.DataFrame(
    department_records,
    columns=[
        "DepartmentID",
        "DepartmentName",
        "FacilityName",
        "DepartmentType",
        "City",
        "State"
    ]
)

departments_df.head()

,DepartmentID,DepartmentName,FacilityName,DepartmentType,City,State
0,DEP001,Emergency Department,RiverCare Central Hospital,Emergency,Richmond,VA
1,DEP002,General Medicine,RiverCare Central Hospital,Inpatient,Richmond,VA
2,DEP003,Cardiology,RiverCare Central Hospital,Specialty,Richmond,VA
3,DEP004,Neurology,RiverCare Central Hospital,Specialty,Richmond,VA
4,DEP005,Orthopedics,RiverCare Central Hospital,Specialty,Richmond,VA

In [16]:
print("Total rows:", len(departments_df))
print("Total columns:", len(departments_df.columns))
print("Duplicate Department IDs:", departments_df["DepartmentID"].duplicated().sum())
print("Missing Department IDs:", departments_df["DepartmentID"].isna().sum())

Total rows: 25
Total columns: 6
Duplicate Department IDs: 0
Missing Department IDs: 0

In [17]:
approved_department_types = [
    "Emergency",
    "Inpatient",
    "Specialty",
    "Primary Care",
    "Outpatient",
    "Behavioral Health"
]

invalid_types = departments_df[
    ~departments_df["DepartmentType"].isin(approved_department_types)
]

print("Invalid Department Types:", len(invalid_types))

Invalid Department Types: 0

In [18]:
departments_df.groupby("FacilityName")["DepartmentID"].count()

FacilityName
RiverCare Central Hospital       6
RiverCare Community Clinic       5
RiverCare Downtown Clinic        4
RiverCare North Hospital         5
RiverCare West Medical Center    5
Name: DepartmentID, dtype: int64

In [19]:
departments_df.to_csv(
    RAW_DATA_PATH / "departments.csv",
    index=False
)

print("departments.csv created successfully.")

departments.csv created successfully.

In [20]:
payer_records = [
    ("PAY01", "Medicare", "Government"),
    ("PAY02", "Medicaid", "Government"),
    ("PAY03", "Commercial Insurance", "Commercial"),
    ("PAY04", "Employer Sponsored", "Commercial"),
    ("PAY05", "Self Pay", "Self Pay"),
    ("PAY06", "Other", "Other")
]

In [21]:
payers_df = pd.DataFrame(
    payer_records,
    columns=[
        "PayerID",
        "PayerName",
        "PayerType"
    ]
)

payers_df

  PayerID             PayerName   PayerType
0   PAY01              Medicare  Government
1   PAY02              Medicaid  Government
2   PAY03  Commercial Insurance  Commercial
3   PAY04    Employer Sponsored  Commercial
4   PAY05              Self Pay    Self Pay
5   PAY06                 Other       Other

In [22]:
print("Total rows:", len(payers_df))
print("Duplicate Payer IDs:", payers_df["PayerID"].duplicated().sum())
print("Missing Payer IDs:", payers_df["PayerID"].isna().sum())
print("Missing Payer Names:", payers_df["PayerName"].isna().sum())

Total rows: 6
Duplicate Payer IDs: 0
Missing Payer IDs: 0
Missing Payer Names: 0

In [23]:
approved_payer_types = [
    "Government",
    "Commercial",
    "Self Pay",
    "Other"
]

invalid_payer_types = payers_df[
    ~payers_df["PayerType"].isin(approved_payer_types)
]

print("Invalid Payer Types:", len(invalid_payer_types))

Invalid Payer Types: 0

In [24]:
payers_df["PayerType"].value_counts()

PayerType
Government    2
Commercial    2
Self Pay      1
Other         1
Name: count, dtype: int64

In [25]:
payers_df.to_csv(
    RAW_DATA_PATH / "payers.csv",
    index=False
)

print("payers.csv created successfully.")

payers.csv created successfully.

In [26]:
diagnosis_records = [
    ("DX001", "E11", "Type 2 Diabetes", "Diabetes", 1),
    ("DX002", "E10", "Type 1 Diabetes", "Diabetes", 1),
    ("DX003", "I10", "Essential Hypertension", "Hypertension", 1),
    ("DX004", "I50", "Heart Failure", "Heart Disease", 1),
    ("DX005", "I25", "Coronary Artery Disease", "Heart Disease", 1),
    ("DX006", "J44", "Chronic Obstructive Pulmonary Disease", "COPD", 1),
    ("DX007", "J45", "Asthma", "Asthma", 1),
    ("DX008", "N18", "Chronic Kidney Disease", "Kidney Disease", 1),
    ("DX009", "J06", "Acute Upper Respiratory Infection", "Respiratory", 0),
    ("DX010", "J18", "Pneumonia", "Respiratory", 0),
    ("DX011", "J10", "Influenza", "Infectious Disease", 0),
    ("DX012", "A09", "Infectious Gastroenteritis", "Infectious Disease", 0),
    ("DX013", "S72", "Hip Fracture", "Injury", 0),
    ("DX014", "S52", "Forearm Fracture", "Injury", 0),
    ("DX015", "M17", "Knee Osteoarthritis", "Musculoskeletal", 1),
    ("DX016", "M54", "Low Back Pain", "Musculoskeletal", 0),
    ("DX017", "F32", "Major Depressive Disorder", "Mental Health", 1),
    ("DX018", "F41", "Anxiety Disorder", "Mental Health", 1),
    ("DX019", "G43", "Migraine", "Neurological", 1),
    ("DX020", "G40", "Epilepsy", "Neurological", 1),
    ("DX021", "K21", "Gastroesophageal Reflux Disease", "Gastrointestinal", 1),
    ("DX022", "K52", "Noninfective Gastroenteritis", "Gastrointestinal", 0),
    ("DX023", "C50", "Breast Cancer", "Cancer", 1),
    ("DX024", "C34", "Lung Cancer", "Cancer", 1),
    ("DX025", "C18", "Colon Cancer", "Cancer", 1),
    ("DX026", "E78", "Hyperlipidemia", "Other", 1),
    ("DX027", "D64", "Anemia", "Other", 0),
    ("DX028", "R07", "Chest Pain", "Other", 0),
    ("DX029", "R10", "Abdominal Pain", "Other", 0),
    ("DX030", "R51", "Headache", "Other", 0),
    ("DX031", "I48", "Atrial Fibrillation", "Heart Disease", 1),
    ("DX032", "I63", "Ischemic Stroke", "Neurological", 0),
    ("DX033", "J20", "Acute Bronchitis", "Respiratory", 0),
    ("DX034", "J30", "Allergic Rhinitis", "Respiratory", 1),
    ("DX035", "N39", "Urinary Tract Infection", "Infectious Disease", 0),
    ("DX036", "L03", "Cellulitis", "Infectious Disease", 0),
    ("DX037", "M06", "Rheumatoid Arthritis", "Musculoskeletal", 1),
    ("DX038", "M81", "Osteoporosis", "Musculoskeletal", 1),
    ("DX039", "F20", "Schizophrenia", "Mental Health", 1),
    ("DX040", "F31", "Bipolar Disorder", "Mental Health", 1),
    ("DX041", "G20", "Parkinson Disease", "Neurological", 1),
    ("DX042", "G30", "Alzheimer Disease", "Neurological", 1),
    ("DX043", "K74", "Cirrhosis", "Gastrointestinal", 1),
    ("DX044", "K80", "Gallstone Disease", "Gastrointestinal", 0),
    ("DX045", "C61", "Prostate Cancer", "Cancer", 1),
    ("DX046", "C43", "Melanoma", "Cancer", 1),
    ("DX047", "E03", "Hypothyroidism", "Other", 1),
    ("DX048", "E66", "Obesity", "Other", 1),
    ("DX049", "R42", "Dizziness", "Other", 0),
    ("DX050", "R55", "Syncope", "Other", 0)
]

In [27]:
diagnoses_df = pd.DataFrame(
    diagnosis_records,
    columns=[
        "DiagnosisID",
        "DiagnosisCode",
        "DiagnosisName",
        "DiagnosisCategory",
        "ChronicConditionFlag"
    ]
)

diagnoses_df.head()

,DiagnosisID,DiagnosisCode,DiagnosisName,DiagnosisCategory,ChronicConditionFlag
0,DX001,E11,Type 2 Diabetes,Diabetes,1
1,DX002,E10,Type 1 Diabetes,Diabetes,1
2,DX003,I10,Essential Hypertension,Hypertension,1
3,DX004,I50,Heart Failure,Heart Disease,1
4,DX005,I25,Coronary Artery Disease,Heart Disease,1

In [28]:
print("Total rows:", len(diagnoses_df))
print("Duplicate Diagnosis IDs:", diagnoses_df["DiagnosisID"].duplicated().sum())
print("Duplicate Diagnosis Codes:", diagnoses_df["DiagnosisCode"].duplicated().sum())
print("Missing Diagnosis Names:", diagnoses_df["DiagnosisName"].isna().sum())

Total rows: 50
Duplicate Diagnosis IDs: 0
Duplicate Diagnosis Codes: 0
Missing Diagnosis Names: 0

In [29]:
approved_diagnosis_categories = [
    "Diabetes",
    "Hypertension",
    "Heart Disease",
    "COPD",
    "Asthma",
    "Kidney Disease",
    "Respiratory",
    "Infectious Disease",
    "Injury",
    "Musculoskeletal",
    "Mental Health",
    "Neurological",
    "Gastrointestinal",
    "Cancer",
    "Other"
]

invalid_categories = diagnoses_df[
    ~diagnoses_df["DiagnosisCategory"].isin(approved_diagnosis_categories)
]

print("Invalid Diagnosis Categories:", len(invalid_categories))

Invalid Diagnosis Categories: 0

In [30]:
invalid_chronic_flags = diagnoses_df[
    ~diagnoses_df["ChronicConditionFlag"].isin([0, 1])
]

print("Invalid ChronicConditionFlag values:", len(invalid_chronic_flags))

Invalid ChronicConditionFlag values: 0

In [31]:
diagnoses_df["ChronicConditionFlag"].value_counts()

ChronicConditionFlag
1    31
0    19
Name: count, dtype: int64

In [32]:
diagnoses_df.to_csv(
    RAW_DATA_PATH / "diagnoses.csv",
    index=False
)

print("diagnoses.csv created successfully.")

diagnoses.csv created successfully.

In [33]:
procedure_records = [
    ("PROC001", "PR001", "Complete Blood Count", "Laboratory", 85.00),
    ("PROC002", "PR002", "Basic Metabolic Panel", "Laboratory", 95.00),
    ("PROC003", "PR003", "HbA1c Test", "Laboratory", 70.00),
    ("PROC004", "PR004", "Lipid Panel", "Laboratory", 90.00),
    ("PROC005", "PR005", "Urinalysis", "Laboratory", 55.00),

    ("PROC006", "PR006", "Chest X-Ray", "Imaging", 220.00),
    ("PROC007", "PR007", "Abdominal X-Ray", "Imaging", 240.00),
    ("PROC008", "PR008", "CT Scan - Head", "Imaging", 850.00),
    ("PROC009", "PR009", "CT Scan - Chest", "Imaging", 950.00),
    ("PROC010", "PR010", "MRI - Brain", "Imaging", 1450.00),
    ("PROC011", "PR011", "MRI - Spine", "Imaging", 1550.00),
    ("PROC012", "PR012", "Ultrasound", "Imaging", 480.00),

    ("PROC013", "PR013", "Electrocardiogram", "Diagnostic", 180.00),
    ("PROC014", "PR014", "Echocardiogram", "Diagnostic", 625.00),
    ("PROC015", "PR015", "Pulmonary Function Test", "Diagnostic", 350.00),
    ("PROC016", "PR016", "Stress Test", "Diagnostic", 675.00),
    ("PROC017", "PR017", "EEG", "Diagnostic", 525.00),
    ("PROC018", "PR018", "Endoscopy", "Diagnostic", 1250.00),

    ("PROC019", "PR019", "IV Fluid Administration", "Therapeutic", 150.00),
    ("PROC020", "PR020", "Nebulizer Treatment", "Therapeutic", 130.00),
    ("PROC021", "PR021", "Wound Care", "Therapeutic", 175.00),
    ("PROC022", "PR022", "Medication Infusion", "Therapeutic", 420.00),
    ("PROC023", "PR023", "Dialysis Session", "Therapeutic", 900.00),

    ("PROC024", "PR024", "Appendectomy", "Surgical", 8200.00),
    ("PROC025", "PR025", "Gallbladder Surgery", "Surgical", 9600.00),
    ("PROC026", "PR026", "Knee Arthroscopy", "Surgical", 7800.00),
    ("PROC027", "PR027", "Hip Replacement", "Surgical", 24500.00),
    ("PROC028", "PR028", "Cardiac Catheterization", "Surgical", 12500.00),
    ("PROC029", "PR029", "Minor Surgical Procedure", "Surgical", 1800.00),

    ("PROC030", "PR030", "Physical Therapy Session", "Rehabilitation", 160.00),
    ("PROC031", "PR031", "Occupational Therapy Session", "Rehabilitation", 170.00),
    ("PROC032", "PR032", "Speech Therapy Session", "Rehabilitation", 165.00),

    ("PROC033", "PR033", "Annual Physical Examination", "Preventive", 210.00),
    ("PROC034", "PR034", "Vaccination", "Preventive", 75.00),
    ("PROC035", "PR035", "Cancer Screening", "Preventive", 450.00),
    ("PROC036", "PR036", "Diabetes Screening", "Preventive", 120.00),
    ("PROC037", "PR037", "Blood Pressure Screening", "Preventive", 45.00),

    ("PROC038", "PR038", "Colonoscopy", "Diagnostic", 1600.00),
    ("PROC039", "PR039", "Mammography", "Imaging", 350.00),
    ("PROC040", "PR040", "Bone Density Scan", "Imaging", 300.00)
]

In [34]:
procedures_df = pd.DataFrame(
    procedure_records,
    columns=[
        "ProcedureID",
        "ProcedureCode",
        "ProcedureName",
        "ProcedureCategory",
        "StandardCost"
    ]
)

procedures_df.head()

,ProcedureID,ProcedureCode,ProcedureName,ProcedureCategory,StandardCost
0,PROC001,PR001,Complete Blood Count,Laboratory,85.0
1,PROC002,PR002,Basic Metabolic Panel,Laboratory,95.0
2,PROC003,PR003,HbA1c Test,Laboratory,70.0
3,PROC004,PR004,Lipid Panel,Laboratory,90.0
4,PROC005,PR005,Urinalysis,Laboratory,55.0

In [35]:
print("Total rows:", len(procedures_df))
print("Duplicate Procedure IDs:", procedures_df["ProcedureID"].duplicated().sum())
print("Duplicate Procedure Codes:", procedures_df["ProcedureCode"].duplicated().sum())
print("Missing Procedure Names:", procedures_df["ProcedureName"].isna().sum())

Total rows: 40
Duplicate Procedure IDs: 0
Duplicate Procedure Codes: 0
Missing Procedure Names: 0

In [36]:
approved_procedure_categories = [
    "Laboratory",
    "Imaging",
    "Diagnostic",
    "Therapeutic",
    "Surgical",
    "Rehabilitation",
    "Preventive"
]

invalid_procedure_categories = procedures_df[
    ~procedures_df["ProcedureCategory"].isin(approved_procedure_categories)
]

print("Invalid Procedure Categories:", len(invalid_procedure_categories))

Invalid Procedure Categories: 0

In [37]:
invalid_costs = procedures_df[
    procedures_df["StandardCost"] < 0
]

print("Negative Standard Costs:", len(invalid_costs))

Negative Standard Costs: 0

In [38]:
procedures_df["ProcedureCategory"].value_counts()

ProcedureCategory
Imaging           9
Diagnostic        7
Surgical          6
Laboratory        5
Therapeutic       5
Preventive        5
Rehabilitation    3
Name: count, dtype: int64

In [39]:
procedures_df["StandardCost"].describe()

count       40.000000
mean      1989.000000
std       4627.821135
min         45.000000
25%        157.500000
50%        350.000000
75%       1025.000000
max      24500.000000
Name: StandardCost, dtype: float64

In [40]:
procedures_df.to_csv(
    RAW_DATA_PATH / "procedures.csv",
    index=False
)

print("procedures.csv created successfully.")

procedures.csv created successfully.

In [41]:
specialty_map = {
    "Emergency Department": "Emergency Medicine",
    "General Medicine": "Internal Medicine",
    "Cardiology": "Cardiology",
    "Neurology": "Neurology",
    "Orthopedics": "Orthopedics",
    "Oncology": "Oncology",
    "Pediatrics": "Pediatrics",
    "Pulmonology": "Pulmonology",
    "Gastroenterology": "Gastroenterology",
    "Endocrinology": "Endocrinology",
    "Primary Care": "Family Medicine",
    "Behavioral Health": "Psychiatry"
}

In [42]:
provider_types = [
    "Physician",
    "Nurse Practitioner",
    "Physician Assistant"
]

provider_type_probabilities = [
    0.65,
    0.20,
    0.15
]

In [43]:
department_ids = departments_df["DepartmentID"].tolist()

provider_department_assignments = []

# Give every department at least 4 providers
for department_id in department_ids:
    provider_department_assignments.extend([department_id] * 4)

print("Providers after minimum assignment:",
      len(provider_department_assignments))

Providers after minimum assignment: 100

In [44]:
additional_departments = np.random.choice(
    department_ids,
    size=20,
    replace=True
)

provider_department_assignments.extend(additional_departments)

print("Total provider assignments:",
      len(provider_department_assignments))

Total provider assignments: 120

In [45]:
random.shuffle(provider_department_assignments)

In [46]:
provider_records = []

hire_start = datetime(2012, 1, 1)
hire_end = datetime(2025, 12, 31)

hire_range_days = (hire_end - hire_start).days

for i in range(120):

    provider_id = f"PRV{i + 1:03d}"

    department_id = provider_department_assignments[i]

    department_name = departments_df.loc[
        departments_df["DepartmentID"] == department_id,
        "DepartmentName"
    ].iloc[0]

    specialty = specialty_map[department_name]

    provider_type = np.random.choice(
        provider_types,
        p=provider_type_probabilities
    )

    random_days = random.randint(0, hire_range_days)

    hire_date = (
        hire_start + timedelta(days=random_days)
    ).date()

    active_flag = np.random.choice(
        [1, 0],
        p=[0.92, 0.08]
    )

    provider_records.append(
        (
            provider_id,
            department_id,
            provider_type,
            specialty,
            hire_date,
            active_flag
        )
    )

In [47]:
providers_df = pd.DataFrame(
    provider_records,
    columns=[
        "ProviderID",
        "DepartmentID",
        "ProviderType",
        "Specialty",
        "HireDate",
        "ActiveFlag"
    ]
)

providers_df.head()

,ProviderID,DepartmentID,ProviderType,Specialty,HireDate,ActiveFlag
0,PRV001,DEP003,Nurse Practitioner,Cardiology,2015-02-07,0
1,PRV002,DEP022,Physician,Pediatrics,2023-06-06,0
2,PRV003,DEP024,Physician,Pulmonology,2023-01-25,1
3,PRV004,DEP008,Physician,Internal Medicine,2014-01-14,1
4,PRV005,DEP024,Physician,Pulmonology,2013-01-20,1

In [48]:
print("Total rows:", len(providers_df))
print("Total columns:", len(providers_df.columns))

Total rows: 120
Total columns: 6

In [49]:
print(
    "Duplicate Provider IDs:",
    providers_df["ProviderID"].duplicated().sum()
)

print(
    "Missing Provider IDs:",
    providers_df["ProviderID"].isna().sum()
)

Duplicate Provider IDs: 0
Missing Provider IDs: 0

In [50]:
invalid_department_refs = providers_df[
    ~providers_df["DepartmentID"].isin(
        departments_df["DepartmentID"]
    )
]

print(
    "Invalid Department References:",
    len(invalid_department_refs)
)

Invalid Department References: 0

In [51]:
approved_provider_types = [
    "Physician",
    "Nurse Practitioner",
    "Physician Assistant"
]

invalid_provider_types = providers_df[
    ~providers_df["ProviderType"].isin(
        approved_provider_types
    )
]

print(
    "Invalid Provider Types:",
    len(invalid_provider_types)
)

Invalid Provider Types: 0

In [52]:
invalid_active_flags = providers_df[
    ~providers_df["ActiveFlag"].isin([0, 1])
]

print(
    "Invalid ActiveFlag values:",
    len(invalid_active_flags)
)

Invalid ActiveFlag values: 0

In [53]:
providers_df["ActiveFlag"].value_counts()

ActiveFlag
1    105
0     15
Name: count, dtype: int64

In [54]:
provider_check_df = providers_df.merge(
    departments_df[
        ["DepartmentID", "DepartmentName"]
    ],
    on="DepartmentID",
    how="left"
)

provider_check_df["ExpectedSpecialty"] = (
    provider_check_df["DepartmentName"]
    .map(specialty_map)
)

specialty_mismatches = provider_check_df[
    provider_check_df["Specialty"]
    != provider_check_df["ExpectedSpecialty"]
]

print(
    "Specialty / Department mismatches:",
    len(specialty_mismatches)
)

Specialty / Department mismatches: 0

In [55]:
provider_distribution = (
    providers_df
    .merge(
        departments_df[
            [
                "DepartmentID",
                "DepartmentName",
                "FacilityName"
            ]
        ],
        on="DepartmentID",
        how="left"
    )
)

provider_distribution.groupby(
    "FacilityName"
)["ProviderID"].count()

FacilityName
RiverCare Central Hospital       27
RiverCare Community Clinic       27
RiverCare Downtown Clinic        18
RiverCare North Hospital         27
RiverCare West Medical Center    21
Name: ProviderID, dtype: int64

In [56]:
providers_df["Specialty"].value_counts()

Specialty
Cardiology            18
Internal Medicine     15
Emergency Medicine    14
Pulmonology           13
Family Medicine       11
Pediatrics             9
Psychiatry             9
Endocrinology          9
Orthopedics            8
Gastroenterology       5
Neurology              5
Oncology               4
Name: count, dtype: int64

In [57]:
providers_df["ProviderType"].value_counts()

ProviderType
Physician              80
Nurse Practitioner     23
Physician Assistant    17
Name: count, dtype: int64

In [58]:
providers_df.to_csv(
    RAW_DATA_PATH / "providers.csv",
    index=False
)

print("providers.csv created successfully.")

providers.csv created successfully.

In [59]:
patient_count = 10_000

gender_values = [
    "Male",
    "Female",
    "Other",
    "Unknown"
]

gender_probabilities = [
    0.485,
    0.495,
    0.01,
    0.01
]

race_values = [
    "White",
    "Black or African American",
    "Asian",
    "American Indian or Alaska Native",
    "Native Hawaiian or Other Pacific Islander",
    "Multiple",
    "Other",
    "Unknown"
]

race_probabilities = [
    0.50,
    0.25,
    0.10,
    0.02,
    0.01,
    0.05,
    0.04,
    0.03
]

ethnicity_values = [
    "Hispanic or Latino",
    "Not Hispanic or Latino",
    "Unknown"
]

ethnicity_probabilities = [
    0.12,
    0.85,
    0.03
]

In [60]:
region_zip_map = {
    "Central": ["23220", "23221", "23223", "23225"],
    "Northern": ["22401", "22405", "22554", "22551"],
    "Southern": ["23803", "23805", "23831", "23834"],
    "Eastern": ["23185", "23601", "23602", "23606"],
    "Western": ["22901", "22902", "22903", "22911"]
}

region_values = [
    "Central",
    "Northern",
    "Southern",
    "Eastern",
    "Western"
]

region_probabilities = [
    0.35,
    0.20,
    0.18,
    0.12,
    0.15
]

In [61]:
age_groups = [
    (0, 17),
    (18, 34),
    (35, 49),
    (50, 64),
    (65, 90)
]

age_group_probabilities = [
    0.18,
    0.20,
    0.20,
    0.22,
    0.20
]

In [62]:
patient_records = []

reference_date = datetime(2025, 12, 31).date()

registration_start = datetime(2023, 1, 1).date()
registration_end = datetime(2025, 12, 31).date()

for i in range(patient_count):

    patient_id = f"PAT{i + 1:06d}"

    # Select age group
    age_group_index = np.random.choice(
        len(age_groups),
        p=age_group_probabilities
    )

    min_age, max_age = age_groups[age_group_index]

    age = random.randint(min_age, max_age)

    # Approximate DOB and randomize within the year
    birth_year = reference_date.year - age

    birth_date = datetime(
        birth_year,
        random.randint(1, 12),
        1
    ).date()

    # Safely choose a valid day within the month
    birth_date = birth_date + timedelta(
        days=random.randint(0, 27)
    )

    gender = np.random.choice(
        gender_values,
        p=gender_probabilities
    )

    race = np.random.choice(
        race_values,
        p=race_probabilities
    )

    ethnicity = np.random.choice(
        ethnicity_values,
        p=ethnicity_probabilities
    )

    region = np.random.choice(
        region_values,
        p=region_probabilities
    )

    zip_code = random.choice(
        region_zip_map[region]
    )

    state = "VA"

    # Registration cannot occur before birth
    earliest_registration = max(
        registration_start,
        birth_date
    )

    registration_range = (
        registration_end - earliest_registration
    ).days

    registration_date = (
        earliest_registration
        + timedelta(
            days=random.randint(0, registration_range)
        )
    )

    patient_records.append(
        (
            patient_id,
            birth_date,
            gender,
            race,
            ethnicity,
            zip_code,
            state,
            region,
            registration_date
        )
    )

In [63]:
patients_clean_df = pd.DataFrame(
    patient_records,
    columns=[
        "PatientID",
        "BirthDate",
        "Gender",
        "Race",
        "Ethnicity",
        "ZipCode",
        "State",
        "Region",
        "RegistrationDate"
    ]
)

patients_clean_df.head()

,PatientID,BirthDate,Gender,Race,Ethnicity,ZipCode,State,Region,RegistrationDate
0,PAT000001,2006-07-24,Male,White,Not Hispanic or Latino,22554,VA,Northern,2023-08-12
1,PAT000002,1953-04-07,Female,White,Not Hispanic or Latino,23834,VA,Southern,2023-10-15
2,PAT000003,1994-03-09,Male,White,Not Hispanic or Latino,23606,VA,Eastern,2024-05-26
3,PAT000004,2023-08-26,Female,Black or African American,Not Hispanic or Latino,22401,VA,Northern,2023-10-16
4,PAT000005,2007-02-25,Female,White,Hispanic or Latino,23805,VA,Southern,2023-12-07

In [64]:
print("Total rows:", len(patients_clean_df))
print("Total columns:", len(patients_clean_df.columns))

Total rows: 10000
Total columns: 9

In [65]:
print(
    "Duplicate Patient IDs:",
    patients_clean_df["PatientID"].duplicated().sum()
)

print(
    "Missing Patient IDs:",
    patients_clean_df["PatientID"].isna().sum()
)

Duplicate Patient IDs: 0
Missing Patient IDs: 0

In [66]:
invalid_birth_registration = patients_clean_df[
    patients_clean_df["BirthDate"]
    > patients_clean_df["RegistrationDate"]
]

print(
    "BirthDate after RegistrationDate:",
    len(invalid_birth_registration)
)

BirthDate after RegistrationDate: 0

In [67]:
future_birth_dates = patients_clean_df[
    patients_clean_df["BirthDate"]
    > reference_date
]

print(
    "Future BirthDates:",
    len(future_birth_dates)
)

Future BirthDates: 0

In [68]:
invalid_genders = patients_clean_df[
    ~patients_clean_df["Gender"].isin(
        gender_values
    )
]

invalid_regions = patients_clean_df[
    ~patients_clean_df["Region"].isin(
        region_values
    )
]

print("Invalid Gender values:", len(invalid_genders))
print("Invalid Region values:", len(invalid_regions))

Invalid Gender values: 0
Invalid Region values: 0

In [69]:
patients_clean_df["Gender"].value_counts()

Gender
Female     5028
Male       4782
Other       103
Unknown      87
Name: count, dtype: int64

In [70]:
patients_clean_df["Region"].value_counts()

Region
Central     3535
Northern    1929
Southern    1902
Western     1436
Eastern     1198
Name: count, dtype: int64

In [71]:
patients_clean_df["Race"].value_counts()

Race
White                                        5075
Black or African American                    2412
Asian                                         975
Multiple                                      511
Other                                         412
Unknown                                       312
American Indian or Alaska Native              209
Native Hawaiian or Other Pacific Islander      94
Name: count, dtype: int64

In [72]:
patients_df = patients_clean_df.copy()

In [73]:
missing_region_indices = np.random.choice(
    patients_df.index,
    size=100,
    replace=False
)

patients_df.loc[
    missing_region_indices,
    "Region"
] = np.nan

In [74]:
gender_issue_indices = np.random.choice(
    patients_df.index,
    size=50,
    replace=False
)

bad_gender_values = [
    "F",
    "M",
    "female",
    "male"
]

patients_df.loc[
    gender_issue_indices,
    "Gender"
] = np.random.choice(
    bad_gender_values,
    size=50
)

In [75]:
future_birth_indices = np.random.choice(
    patients_df.index,
    size=10,
    replace=False
)

future_birthdates = [
    datetime(
        random.randint(2027, 2030),
        random.randint(1, 12),
        random.randint(1, 28)
    ).date()
    for _ in range(10)
]

patients_df.loc[
    future_birth_indices,
    "BirthDate"
] = future_birthdates

In [76]:
duplicate_target_indices = np.random.choice(
    patients_df.index,
    size=20,
    replace=False
)

duplicate_source_indices = np.random.choice(
    patients_df.index.difference(
        duplicate_target_indices
    ),
    size=20,
    replace=False
)

duplicate_ids = patients_df.loc[
    duplicate_source_indices,
    "PatientID"
].values

patients_df.loc[
    duplicate_target_indices,
    "PatientID"
] = duplicate_ids

In [77]:
print(
    "Missing Region:",
    patients_df["Region"].isna().sum()
)

print(
    "Duplicate Patient IDs:",
    patients_df["PatientID"].duplicated().sum()
)

print(
    "Future BirthDates:",
    (
        patients_df["BirthDate"] > reference_date
    ).sum()
)

Missing Region: 100
Duplicate Patient IDs: 20
Future BirthDates: 10

In [78]:
invalid_gender_count = (
    ~patients_df["Gender"].isin(
        gender_values
    )
).sum()

print(
    "Invalid / inconsistent Gender values:",
    invalid_gender_count
)

Invalid / inconsistent Gender values: 50

In [79]:
patients_df.to_csv(
    RAW_DATA_PATH / "patients.csv",
    index=False
)

print("patients.csv created successfully.")

patients.csv created successfully.

In [80]:
random.seed(1001)
np.random.seed(1001)

encounter_count = 90_000

print("Encounter generator initialized.")

Encounter generator initialized.

In [81]:
patients_generation_df = patients_clean_df.copy()

patients_generation_df["BirthDate"] = pd.to_datetime(
    patients_generation_df["BirthDate"]
)

patients_generation_df["RegistrationDate"] = pd.to_datetime(
    patients_generation_df["RegistrationDate"]
)

reference_date = pd.Timestamp("2025-12-31")

patients_generation_df["ReferenceAge"] = (
    (
        reference_date -
        patients_generation_df["BirthDate"]
    ).dt.days / 365.25
).astype(int)

patients_generation_df[
    ["PatientID", "BirthDate", "RegistrationDate", "ReferenceAge"]
].head()

   PatientID  BirthDate RegistrationDate  ReferenceAge
0  PAT000001 2006-07-24       2023-08-12            19
1  PAT000002 1953-04-07       2023-10-15            72
2  PAT000003 1994-03-09       2024-05-26            31
3  PAT000004 2023-08-26       2023-10-16             2
4  PAT000005 2007-02-25       2023-12-07            18

In [82]:
patients_generation_df["UtilizationWeight"] = np.select(
    [
        patients_generation_df["ReferenceAge"] < 18,
        patients_generation_df["ReferenceAge"].between(18, 34),
        patients_generation_df["ReferenceAge"].between(35, 49),
        patients_generation_df["ReferenceAge"].between(50, 64),
        patients_generation_df["ReferenceAge"] >= 65
    ],
    [
        0.80,
        0.75,
        0.90,
        1.20,
        1.50
    ],
    default=1.0
)

patient_probabilities = (
    patients_generation_df["UtilizationWeight"]
    /
    patients_generation_df["UtilizationWeight"].sum()
)

patients_generation_df[
    ["PatientID", "ReferenceAge", "UtilizationWeight"]
].head()

   PatientID  ReferenceAge  UtilizationWeight
0  PAT000001            19               0.75
1  PAT000002            72               1.50
2  PAT000003            31               0.75
3  PAT000004             2               0.80
4  PAT000005            18               0.75

In [83]:
department_generation_df = departments_df.copy()

def get_department_base_weight(department_type):
    weight_map = {
        "Emergency": 3.0,
        "Inpatient": 3.5,
        "Specialty": 2.0,
        "Primary Care": 2.5,
        "Outpatient": 2.0,
        "Behavioral Health": 1.5
    }

    return weight_map.get(department_type, 1.0)


department_generation_df["BaseWeight"] = (
    department_generation_df["DepartmentType"]
    .apply(get_department_base_weight)
)

department_generation_df[
    [
        "DepartmentID",
        "DepartmentName",
        "DepartmentType",
        "BaseWeight"
    ]
]

   DepartmentID        DepartmentName     DepartmentType  BaseWeight
0        DEP001  Emergency Department          Emergency         3.0
1        DEP002      General Medicine          Inpatient         3.5
2        DEP003            Cardiology          Specialty         2.0
3        DEP004             Neurology          Specialty         2.0
4        DEP005           Orthopedics          Specialty         2.0
5        DEP006              Oncology          Specialty         2.0
6        DEP007  Emergency Department          Emergency         3.0
7        DEP008      General Medicine          Inpatient         3.5
8        DEP009            Cardiology          Specialty         2.0
9        DEP010            Pediatrics          Specialty         2.0
10       DEP011           Pulmonology          Specialty         2.0
11       DEP012  Emergency Department          Emergency         3.0
12       DEP013      General Medicine          Inpatient         3.5
13       DEP014            Cardiology          Specialty         2.0
14       DEP015      Gastroenterology          Specialty         2.0
15       DEP016         Endocrinology          Specialty         2.0
16       DEP017          Primary Care       Primary Care         2.5
17       DEP018     Behavioral Health  Behavioral Health         1.5
18       DEP019         Endocrinology         Outpatient         2.0
19       DEP020            Cardiology         Outpatient         2.0
20       DEP021          Primary Care       Primary Care         2.5
21       DEP022            Pediatrics         Outpatient         2.0
22       DEP023     Behavioral Health  Behavioral Health         1.5
23       DEP024           Pulmonology         Outpatient         2.0
24       DEP025           Orthopedics         Outpatient         2.0

In [84]:
department_info = (
    departments_df
    .set_index("DepartmentID")
    [
        [
            "DepartmentName",
            "DepartmentType",
            "FacilityName"
        ]
    ]
    .to_dict("index")
)

providers_by_department = (
    providers_df
    .groupby("DepartmentID")["ProviderID"]
    .apply(list)
    .to_dict()
)

provider_hire_dates = dict(
    zip(
        providers_df["ProviderID"],
        pd.to_datetime(providers_df["HireDate"])
    )
)

payer_name_to_id = dict(
    zip(
        payers_df["PayerName"],
        payers_df["PayerID"]
    )
)

print("Lookup dictionaries created.")

Lookup dictionaries created.

In [85]:
def choose_department(age):

    weights = department_generation_df["BaseWeight"].astype(float).copy()

    # Children use Pediatrics more frequently
    if age < 18:
        pediatric_mask = (
            department_generation_df["DepartmentName"]
            == "Pediatrics"
        )

        weights.loc[pediatric_mask] *= 5.0

        cardiology_mask = (
            department_generation_df["DepartmentName"]
            == "Cardiology"
        )

        weights.loc[cardiology_mask] *= 0.40

    # Older adults use more inpatient, ED, and cardiology services
    elif age >= 65:

        general_medicine_mask = (
            department_generation_df["DepartmentName"]
            == "General Medicine"
        )

        cardiology_mask = (
            department_generation_df["DepartmentName"]
            == "Cardiology"
        )

        emergency_mask = (
            department_generation_df["DepartmentName"]
            == "Emergency Department"
        )

        weights.loc[general_medicine_mask] *= 1.70
        weights.loc[cardiology_mask] *= 1.50
        weights.loc[emergency_mask] *= 1.30

    probabilities = weights / weights.sum()

    return np.random.choice(
        department_generation_df["DepartmentID"],
        p=probabilities
    )

In [86]:
def choose_encounter_type(department_name, department_type):

    if department_name == "Emergency Department":
        return np.random.choice(
            ["Emergency", "Urgent Care"],
            p=[0.90, 0.10]
        )

    if department_type == "Inpatient":
        return "Inpatient"

    if department_type == "Primary Care":
        return "Primary Care"

    if department_type == "Outpatient":
        return np.random.choice(
            ["Outpatient", "Specialist"],
            p=[0.55, 0.45]
        )

    if department_type in [
        "Specialty",
        "Behavioral Health"
    ]:
        return "Specialist"

    return "Outpatient"

In [87]:
def choose_payer(age):

    payer_names = [
        "Medicare",
        "Medicaid",
        "Commercial Insurance",
        "Employer Sponsored",
        "Self Pay",
        "Other"
    ]

    if age >= 65:

        probabilities = [
            0.65,
            0.10,
            0.10,
            0.05,
            0.05,
            0.05
        ]

    elif age < 18:

        probabilities = [
            0.00,
            0.30,
            0.25,
            0.30,
            0.10,
            0.05
        ]

    else:

        probabilities = [
            0.05,
            0.15,
            0.25,
            0.35,
            0.15,
            0.05
        ]

    payer_name = np.random.choice(
        payer_names,
        p=probabilities
    )

    return payer_name_to_id[payer_name]

In [88]:
def generate_arrival_datetime(encounter_date, encounter_type):

    if encounter_type in ["Emergency", "Urgent Care"]:
        hour = random.randint(0, 23)

    elif encounter_type == "Inpatient":
        hour = random.randint(6, 22)

    else:
        hour = random.randint(7, 17)

    minute = random.randint(0, 59)

    return datetime.combine(
        encounter_date,
        datetime.min.time()
    ).replace(
        hour=hour,
        minute=minute
    )

In [89]:
def generate_wait_minutes(
    encounter_type,
    facility_name,
    department_name,
    arrival_datetime
):

    base_wait = {
        "Emergency": 60,
        "Urgent Care": 35,
        "Inpatient": 45,
        "Primary Care": 15,
        "Outpatient": 20,
        "Specialist": 25
    }

    target = base_wait[encounter_type]

    wait_minutes = int(
        np.random.gamma(
            shape=2.0,
            scale=target / 2
        )
    )

    # Simulate an operational bottleneck
    # at RiverCare Central Hospital ED.
    if (
        facility_name == "RiverCare Central Hospital"
        and department_name == "Emergency Department"
    ):
        wait_minutes += 25

    # Evening ED demand
    if (
        encounter_type == "Emergency"
        and arrival_datetime.hour >= 17
    ):
        wait_minutes += 15

    # Weekend pressure
    if arrival_datetime.weekday() >= 5:
        wait_minutes += 10

    return max(wait_minutes, 3)

In [90]:
def generate_encounter_cost(
    encounter_type,
    duration_hours
):

    if encounter_type == "Primary Care":
        cost = np.random.normal(220, 60)

    elif encounter_type == "Outpatient":
        cost = np.random.normal(550, 180)

    elif encounter_type == "Specialist":
        cost = np.random.normal(750, 250)

    elif encounter_type == "Urgent Care":
        cost = np.random.normal(450, 150)

    elif encounter_type == "Emergency":
        cost = np.random.normal(1800, 650)

    elif encounter_type == "Inpatient":
        estimated_days = max(
            duration_hours / 24,
            1
        )

        cost = (
            4000
            + estimated_days * 2200
            + np.random.normal(0, 1200)
        )

    else:
        cost = 500

    return round(
        max(cost, 50),
        2
    )

In [91]:
encounter_records = []

patient_ids = patients_generation_df["PatientID"].values

for i in range(encounter_count):

    # -----------------------------------
    # Select patient
    # -----------------------------------

    patient_index = np.random.choice(
        patients_generation_df.index,
        p=patient_probabilities
    )

    patient_row = patients_generation_df.loc[
        patient_index
    ]

    patient_id = patient_row["PatientID"]
    patient_age = patient_row["ReferenceAge"]

    registration_date = (
        patient_row["RegistrationDate"].date()
    )

    # -----------------------------------
    # Encounter date
    # -----------------------------------

    latest_date = datetime(
        2025, 12, 31
    ).date()

    days_available = (
        latest_date - registration_date
    ).days

    encounter_date = (
        registration_date
        + timedelta(
            days=random.randint(
                0,
                max(days_available, 0)
            )
        )
    )

    # -----------------------------------
    # Department
    # -----------------------------------

    department_id = choose_department(
        patient_age
    )

    department_name = (
        department_info[department_id]
        ["DepartmentName"]
    )

    department_type = (
        department_info[department_id]
        ["DepartmentType"]
    )

    facility_name = (
        department_info[department_id]
        ["FacilityName"]
    )

    # -----------------------------------
    # Encounter type
    # -----------------------------------

    encounter_type = choose_encounter_type(
        department_name,
        department_type
    )

    # -----------------------------------
    # Provider
    # -----------------------------------

    department_providers = (
        providers_by_department[
            department_id
        ]
    )

    provider_id = random.choice(
        department_providers
    )

    # -----------------------------------
    # Payer
    # -----------------------------------

    payer_id = choose_payer(
        patient_age
    )

    # -----------------------------------
    # Arrival
    # -----------------------------------

    arrival_datetime = (
        generate_arrival_datetime(
            encounter_date,
            encounter_type
        )
    )

    # -----------------------------------
    # Encounter status
    # -----------------------------------

    if encounter_type == "Emergency":

        encounter_status = np.random.choice(
            [
                "Completed",
                "Left Without Being Seen",
                "Transferred"
            ],
            p=[
                0.93,
                0.04,
                0.03
            ]
        )

    elif encounter_type == "Inpatient":

        encounter_status = np.random.choice(
            [
                "Completed",
                "Transferred"
            ],
            p=[
                0.96,
                0.04
            ]
        )

    else:

        encounter_status = np.random.choice(
            [
                "Completed",
                "Transferred"
            ],
            p=[
                0.99,
                0.01
            ]
        )

    # -----------------------------------
    # Wait time
    # -----------------------------------

    wait_minutes = generate_wait_minutes(
        encounter_type,
        facility_name,
        department_name,
        arrival_datetime
    )

    # -----------------------------------
    # Triage
    # -----------------------------------

    if encounter_type in [
        "Emergency",
        "Urgent Care",
        "Inpatient"
    ]:

        triage_datetime = (
            arrival_datetime
            + timedelta(
                minutes=random.randint(
                    5,
                    25
                )
            )
        )

    else:

        triage_datetime = pd.NaT

    # -----------------------------------
    # Provider Start / End
    # -----------------------------------

    if (
        encounter_status
        == "Left Without Being Seen"
    ):

        provider_id = None
        provider_start_datetime = pd.NaT

        encounter_end_datetime = (
            arrival_datetime
            + timedelta(
                minutes=random.randint(
                    30,
                    180
                )
            )
        )

        duration_hours = (
            (
                encounter_end_datetime
                - arrival_datetime
            ).total_seconds()
            / 3600
        )

        encounter_cost = round(
            np.random.uniform(
                25,
                100
            ),
            2
        )

    else:

        provider_start_datetime = (
            arrival_datetime
            + timedelta(
                minutes=wait_minutes
            )
        )

        if encounter_type == "Inpatient":

            duration_hours = np.random.uniform(
                24,
                168
            )

        elif encounter_type == "Emergency":

            duration_hours = np.random.uniform(
                1,
                8
            )

        elif encounter_type == "Urgent Care":

            duration_hours = np.random.uniform(
                0.5,
                3
            )

        elif encounter_type == "Primary Care":

            duration_hours = np.random.uniform(
                0.25,
                1.0
            )

        else:

            duration_hours = np.random.uniform(
                0.5,
                3.0
            )

        encounter_end_datetime = (
            provider_start_datetime
            + timedelta(
                hours=float(
                    duration_hours
                )
            )
        )

        encounter_cost = (
            generate_encounter_cost(
                encounter_type,
                duration_hours
            )
        )

    # -----------------------------------
    # Encounter ID
    # -----------------------------------

    encounter_id = (
        f"ENC{i + 1:06d}"
    )

    encounter_records.append(
        (
            encounter_id,
            patient_id,
            provider_id,
            department_id,
            payer_id,
            encounter_date,
            encounter_type,
            arrival_datetime,
            triage_datetime,
            provider_start_datetime,
            encounter_end_datetime,
            encounter_status,
            encounter_cost
        )
    )

In [92]:
encounters_clean_df = pd.DataFrame(
    encounter_records,
    columns=[
        "EncounterID",
        "PatientID",
        "ProviderID",
        "DepartmentID",
        "PayerID",
        "EncounterDate",
        "EncounterType",
        "ArrivalDateTime",
        "TriageDateTime",
        "ProviderStartDateTime",
        "EncounterEndDateTime",
        "EncounterStatus",
        "EncounterCost"
    ]
)

encounters_clean_df.head()

,EncounterID,PatientID,ProviderID,DepartmentID,PayerID,EncounterDate,EncounterType,ArrivalDateTime,TriageDateTime,ProviderStartDateTime,EncounterEndDateTime,EncounterStatus,EncounterCost
0,ENC000001,PAT003057,PRV051,DEP007,PAY03,2024-06-19,Emergency,2024-06-19 02:35:00,2024-06-19 02:52:00,2024-06-19 03:06:00,2024-06-19 08:23:40.750764,Completed,1067.62
1,ENC000002,PAT005801,PRV027,DEP020,PAY01,2025-11-25,Outpatient,2025-11-25 13:46:00,NaT,2025-11-25 14:00:00,2025-11-25 14:49:05.668938,Completed,385.01
2,ENC000003,PAT009821,PRV118,DEP001,PAY06,2025-10-01,Emergency,2025-10-01 18:12:00,2025-10-01 18:36:00,2025-10-01 20:03:00,2025-10-02 01:54:04.601495,Completed,2056.60
3,ENC000004,PAT002460,PRV032,DEP014,PAY05,2023-05-11,Specialist,2023-05-11 14:45:00,NaT,2023-05-11 15:00:00,2023-05-11 17:46:05.286476,Completed,567.31
4,ENC000005,PAT003941,PRV008,DEP022,PAY03,2025-12-16,Outpatient,2025-12-16 15:46:00,NaT,2025-12-16 16:28:00,2025-12-16 17:52:46.320212,Completed,258.00

In [93]:
print(
    "Total encounters:",
    len(encounters_clean_df)
)

print(
    "Total columns:",
    len(encounters_clean_df.columns)
)

Total encounters: 90000
Total columns: 13

In [94]:
print(
    "Duplicate Encounter IDs:",
    encounters_clean_df[
        "EncounterID"
    ].duplicated().sum()
)

print(
    "Missing Encounter IDs:",
    encounters_clean_df[
        "EncounterID"
    ].isna().sum()
)

Duplicate Encounter IDs: 0
Missing Encounter IDs: 0

In [95]:
invalid_patient_refs = encounters_clean_df[
    ~encounters_clean_df[
        "PatientID"
    ].isin(
        patients_clean_df[
            "PatientID"
        ]
    )
]

invalid_department_refs = encounters_clean_df[
    ~encounters_clean_df[
        "DepartmentID"
    ].isin(
        departments_df[
            "DepartmentID"
        ]
    )
]

invalid_payer_refs = encounters_clean_df[
    ~encounters_clean_df[
        "PayerID"
    ].isin(
        payers_df[
            "PayerID"
        ]
    )
]

print(
    "Invalid Patient References:",
    len(invalid_patient_refs)
)

print(
    "Invalid Department References:",
    len(invalid_department_refs)
)

print(
    "Invalid Payer References:",
    len(invalid_payer_refs)
)

Invalid Patient References: 0
Invalid Department References: 0
Invalid Payer References: 0

In [96]:
non_null_providers = encounters_clean_df[
    encounters_clean_df[
        "ProviderID"
    ].notna()
]

invalid_provider_refs = non_null_providers[
    ~non_null_providers[
        "ProviderID"
    ].isin(
        providers_df[
            "ProviderID"
        ]
    )
]

print(
    "Invalid Provider References:",
    len(invalid_provider_refs)
)

Invalid Provider References: 0

In [97]:
completed_provider_encounters = (
    encounters_clean_df[
        encounters_clean_df[
            "ProviderStartDateTime"
        ].notna()
    ]
)

invalid_provider_times = (
    completed_provider_encounters[
        completed_provider_encounters[
            "ProviderStartDateTime"
        ]
        <
        completed_provider_encounters[
            "ArrivalDateTime"
        ]
    ]
)

invalid_end_times = encounters_clean_df[
    encounters_clean_df[
        "EncounterEndDateTime"
    ]
    <
    encounters_clean_df[
        "ArrivalDateTime"
    ]
]

print(
    "Provider starts before arrival:",
    len(invalid_provider_times)
)

print(
    "Encounter ends before arrival:",
    len(invalid_end_times)
)

Provider starts before arrival: 0
Encounter ends before arrival: 0

In [98]:
encounters_clean_df[
    "EncounterType"
].value_counts()

EncounterType
Specialist      42104
Inpatient       17740
Emergency       12610
Outpatient       8812
Primary Care     7313
Urgent Care      1421
Name: count, dtype: int64

In [99]:
encounters_clean_df[
    "EncounterStatus"
].value_counts()

EncounterStatus
Completed                  87784
Transferred                 1715
Left Without Being Seen      501
Name: count, dtype: int64

In [100]:
inpatient_count = (
    encounters_clean_df[
        "EncounterType"
    ]
    .eq("Inpatient")
    .sum()
)

print(
    "Inpatient encounters:",
    inpatient_count
)

Inpatient encounters: 17740

In [101]:
wait_check_df = (
    encounters_clean_df[
        encounters_clean_df[
            "ProviderStartDateTime"
        ].notna()
    ]
    .copy()
)

wait_check_df["WaitMinutes"] = (
    (
        pd.to_datetime(
            wait_check_df[
                "ProviderStartDateTime"
            ]
        )
        -
        pd.to_datetime(
            wait_check_df[
                "ArrivalDateTime"
            ]
        )
    )
    .dt.total_seconds()
    / 60
)

wait_check_df.groupby(
    "EncounterType"
)["WaitMinutes"].mean().round(1)

EncounterType
Emergency       75.0
Inpatient       47.2
Outpatient      22.4
Primary Care    17.4
Specialist      27.3
Urgent Care     44.8
Name: WaitMinutes, dtype: float64

In [102]:
encounters_df = (
    encounters_clean_df.copy()
)

In [103]:
completed_indices = encounters_df[
    encounters_df[
        "EncounterStatus"
    ] == "Completed"
].index

missing_provider_indices = (
    np.random.choice(
        completed_indices,
        size=900,
        replace=False
    )
)

encounters_df.loc[
    missing_provider_indices,
    "ProviderID"
] = np.nan

In [104]:
invalid_department_indices = (
    np.random.choice(
        encounters_df.index,
        size=270,
        replace=False
    )
)

encounters_df.loc[
    invalid_department_indices,
    "DepartmentID"
] = "DEP999"

In [105]:
negative_cost_indices = (
    np.random.choice(
        encounters_df.index,
        size=180,
        replace=False
    )
)

encounters_df.loc[
    negative_cost_indices,
    "EncounterCost"
] = (
    -abs(
        encounters_df.loc[
            negative_cost_indices,
            "EncounterCost"
        ]
    )
)

In [106]:
valid_provider_time_indices = (
    encounters_df[
        encounters_df[
            "ProviderStartDateTime"
        ].notna()
    ].index
)

bad_time_indices = np.random.choice(
    valid_provider_time_indices,
    size=450,
    replace=False
)

encounters_df.loc[
    bad_time_indices,
    "ProviderStartDateTime"
] = (
    pd.to_datetime(
        encounters_df.loc[
            bad_time_indices,
            "ArrivalDateTime"
        ]
    )
    -
    pd.to_timedelta(
        np.random.randint(
            5,
            61,
            size=450
        ),
        unit="m"
    )
)

In [107]:
bad_type_indices = np.random.choice(
    encounters_df.index,
    size=450,
    replace=False
)

bad_encounter_types = [
    "ER",
    "emergency",
    "Out Patient",
    "PrimaryCare",
    "SPECIALIST"
]

encounters_df.loc[
    bad_type_indices,
    "EncounterType"
] = np.random.choice(
    bad_encounter_types,
    size=450
)

In [108]:
approved_encounter_types = [
    "Emergency",
    "Inpatient",
    "Outpatient",
    "Urgent Care",
    "Primary Care",
    "Specialist"
]

completed_missing_provider = (
    (
        encounters_df[
            "EncounterStatus"
        ] == "Completed"
    )
    &
    (
        encounters_df[
            "ProviderID"
        ].isna()
    )
).sum()

invalid_department_count = (
    ~encounters_df[
        "DepartmentID"
    ].isin(
        departments_df[
            "DepartmentID"
        ]
    )
).sum()

negative_cost_count = (
    encounters_df[
        "EncounterCost"
    ] < 0
).sum()

bad_provider_time_count = (
    (
        pd.to_datetime(
            encounters_df[
                "ProviderStartDateTime"
            ]
        )
        <
        pd.to_datetime(
            encounters_df[
                "ArrivalDateTime"
            ]
        )
    )
).sum()

invalid_encounter_type_count = (
    ~encounters_df[
        "EncounterType"
    ].isin(
        approved_encounter_types
    )
).sum()

print(
    "Completed encounters missing Provider:",
    completed_missing_provider
)

print(
    "Invalid Department references:",
    invalid_department_count
)

print(
    "Negative costs:",
    negative_cost_count
)

print(
    "Provider start before arrival:",
    bad_provider_time_count
)

print(
    "Invalid EncounterType values:",
    invalid_encounter_type_count
)

Completed encounters missing Provider: 900
Invalid Department references: 270
Negative costs: 180
Provider start before arrival: 450
Invalid EncounterType values: 450

In [109]:
encounters_df.to_csv(
    RAW_DATA_PATH / "encounters.csv",
    index=False
)

print(
    "encounters.csv created successfully."
)

encounters.csv created successfully.

In [110]:
random.seed(2001)
np.random.seed(2001)

print("Encounter diagnosis generator initialized.")

Encounter diagnosis generator initialized.

In [111]:
diagnosis_groups = {
    "diabetes": ["DX001", "DX002"],
    
    "hypertension": ["DX003"],
    
    "heart": [
        "DX004", "DX005", "DX031", "DX028"
    ],
    
    "respiratory": [
        "DX006", "DX007", "DX009",
        "DX010", "DX011", "DX033", "DX034"
    ],
    
    "kidney": [
        "DX008", "DX035"
    ],
    
    "injury": [
        "DX013", "DX014"
    ],
    
    "musculoskeletal": [
        "DX015", "DX016", "DX037", "DX038"
    ],
    
    "mental_health": [
        "DX017", "DX018", "DX039", "DX040"
    ],
    
    "neurological": [
        "DX019", "DX020", "DX032",
        "DX041", "DX042", "DX049", "DX050"
    ],
    
    "gastrointestinal": [
        "DX012", "DX021", "DX022",
        "DX029", "DX043", "DX044"
    ],
    
    "cancer": [
        "DX023", "DX024", "DX025",
        "DX045", "DX046"
    ],
    
    "general": [
        "DX026", "DX027", "DX028",
        "DX029", "DX030", "DX047", "DX048"
    ]
}

In [112]:
patient_age_lookup = dict(
    zip(
        patients_generation_df["PatientID"],
        patients_generation_df["ReferenceAge"]
    )
)

print("Patient age lookup created.")

Patient age lookup created.

In [113]:
def choose_primary_diagnosis(
    patient_age,
    department_name,
    encounter_type
):

    # Pediatrics / younger patients
    if patient_age < 18:
        pool = (
            diagnosis_groups["respiratory"] * 4
            + diagnosis_groups["general"] * 2
            + diagnosis_groups["injury"] * 2
            + diagnosis_groups["gastrointestinal"]
        )

    # Cardiology
    elif department_name == "Cardiology":
        pool = (
            diagnosis_groups["heart"] * 6
            + diagnosis_groups["hypertension"] * 4
            + diagnosis_groups["diabetes"] * 2
            + diagnosis_groups["general"]
        )

    # Endocrinology
    elif department_name == "Endocrinology":
        pool = (
            diagnosis_groups["diabetes"] * 6
            + diagnosis_groups["general"] * 3
            + diagnosis_groups["hypertension"] * 2
        )

    # Pulmonology
    elif department_name == "Pulmonology":
        pool = (
            diagnosis_groups["respiratory"] * 6
            + diagnosis_groups["general"]
        )

    # Neurology
    elif department_name == "Neurology":
        pool = (
            diagnosis_groups["neurological"] * 6
            + diagnosis_groups["general"]
        )

    # Orthopedics
    elif department_name == "Orthopedics":
        pool = (
            diagnosis_groups["musculoskeletal"] * 5
            + diagnosis_groups["injury"] * 4
            + diagnosis_groups["general"]
        )

    # Oncology
    elif department_name == "Oncology":
        pool = (
            diagnosis_groups["cancer"] * 7
            + diagnosis_groups["general"]
        )

    # Behavioral Health
    elif department_name == "Behavioral Health":
        pool = (
            diagnosis_groups["mental_health"] * 8
            + diagnosis_groups["general"]
        )

    # Gastroenterology
    elif department_name == "Gastroenterology":
        pool = (
            diagnosis_groups["gastrointestinal"] * 7
            + diagnosis_groups["general"]
        )

    # Emergency
    elif encounter_type in ["Emergency", "Urgent Care"]:
        pool = (
            diagnosis_groups["heart"] * 2
            + diagnosis_groups["respiratory"] * 3
            + diagnosis_groups["injury"] * 3
            + diagnosis_groups["gastrointestinal"] * 2
            + diagnosis_groups["neurological"] * 2
            + diagnosis_groups["general"] * 3
        )

    # Older adults
    elif patient_age >= 65:
        pool = (
            diagnosis_groups["heart"] * 3
            + diagnosis_groups["hypertension"] * 3
            + diagnosis_groups["diabetes"] * 2
            + diagnosis_groups["kidney"] * 2
            + diagnosis_groups["respiratory"] * 2
            + diagnosis_groups["general"] * 2
        )

    # General adult population
    else:
        pool = (
            diagnosis_groups["general"] * 3
            + diagnosis_groups["hypertension"] * 2
            + diagnosis_groups["diabetes"]
            + diagnosis_groups["respiratory"] * 2
            + diagnosis_groups["musculoskeletal"] * 2
            + diagnosis_groups["mental_health"]
            + diagnosis_groups["gastrointestinal"]
        )

    return random.choice(pool)

In [114]:
diagnosis_groups["heart"] * 6

['DX004',
 'DX005',
 'DX031',
 'DX028',
 'DX004',
 'DX005',
 'DX031',
 'DX028',
 'DX004',
 'DX005',
 'DX031',
 'DX028',
 'DX004',
 'DX005',
 'DX031',
 'DX028',
 'DX004',
 'DX005',
 'DX031',
 'DX028',
 'DX004',
 'DX005',
 'DX031',
 'DX028']

In [115]:
def choose_secondary_diagnosis(
    patient_age,
    primary_diagnosis
):

    if patient_age >= 65:
        pool = (
            diagnosis_groups["hypertension"] * 4
            + diagnosis_groups["diabetes"] * 3
            + diagnosis_groups["heart"] * 3
            + diagnosis_groups["kidney"] * 2
            + diagnosis_groups["respiratory"] * 2
            + diagnosis_groups["general"]
        )

    elif patient_age >= 50:
        pool = (
            diagnosis_groups["hypertension"] * 3
            + diagnosis_groups["diabetes"] * 2
            + diagnosis_groups["heart"] * 2
            + diagnosis_groups["general"] * 2
            + diagnosis_groups["musculoskeletal"]
        )

    elif patient_age >= 18:
        pool = (
            diagnosis_groups["general"] * 3
            + diagnosis_groups["mental_health"]
            + diagnosis_groups["respiratory"]
            + diagnosis_groups["musculoskeletal"]
            + diagnosis_groups["hypertension"]
        )

    else:
        pool = (
            diagnosis_groups["respiratory"] * 3
            + diagnosis_groups["general"] * 2
        )

    # Avoid immediately returning the primary diagnosis
    filtered_pool = [
        diagnosis_id
        for diagnosis_id in pool
        if diagnosis_id != primary_diagnosis
    ]

    return random.choice(filtered_pool)

In [116]:
secondary_diagnosis_counts = [0, 1, 2]

secondary_diagnosis_probabilities = [
    0.45,
    0.40,
    0.15
]

In [117]:
encounter_diagnosis_records = []

encounter_diagnosis_counter = 1

for _, encounter in encounters_clean_df.iterrows():

    encounter_id = encounter["EncounterID"]
    patient_id = encounter["PatientID"]
    department_id = encounter["DepartmentID"]
    encounter_type = encounter["EncounterType"]

    patient_age = patient_age_lookup[
        patient_id
    ]

    department_name = (
        department_info[
            department_id
        ]["DepartmentName"]
    )

    # -----------------------------
    # Primary Diagnosis
    # -----------------------------

    primary_diagnosis = (
        choose_primary_diagnosis(
            patient_age,
            department_name,
            encounter_type
        )
    )

    encounter_diagnosis_records.append(
        (
            f"EDX{encounter_diagnosis_counter:07d}",
            encounter_id,
            primary_diagnosis,
            "Primary",
            1 if encounter_type == "Inpatient" else None
        )
    )

    encounter_diagnosis_counter += 1

    # -----------------------------
    # Secondary Diagnoses
    # -----------------------------

    secondary_count = np.random.choice(
        secondary_diagnosis_counts,
        p=secondary_diagnosis_probabilities
    )

    selected_diagnoses = {
        primary_diagnosis
    }

    for _ in range(secondary_count):

        secondary_diagnosis = (
            choose_secondary_diagnosis(
                patient_age,
                primary_diagnosis
            )
        )

        # Avoid duplicate diagnosis within same encounter
        attempts = 0

        while (
            secondary_diagnosis
            in selected_diagnoses
            and attempts < 10
        ):
            secondary_diagnosis = (
                choose_secondary_diagnosis(
                    patient_age,
                    primary_diagnosis
                )
            )

            attempts += 1

        if secondary_diagnosis in selected_diagnoses:
            continue

        selected_diagnoses.add(
            secondary_diagnosis
        )

        if encounter_type == "Inpatient":
            present_on_admission = np.random.choice(
                [1, 0],
                p=[0.85, 0.15]
            )
        else:
            present_on_admission = None

        encounter_diagnosis_records.append(
            (
                f"EDX{encounter_diagnosis_counter:07d}",
                encounter_id,
                secondary_diagnosis,
                "Secondary",
                present_on_admission
            )
        )

        encounter_diagnosis_counter += 1

In [118]:
encounter_diagnoses_clean_df = pd.DataFrame(
    encounter_diagnosis_records,
    columns=[
        "EncounterDiagnosisID",
        "EncounterID",
        "DiagnosisID",
        "DiagnosisType",
        "PresentOnAdmissionFlag"
    ]
)

encounter_diagnoses_clean_df.head()

,EncounterDiagnosisID,EncounterID,DiagnosisID,DiagnosisType,PresentOnAdmissionFlag
0,EDX0000001,ENC000001,DX026,Primary,NaN
1,EDX0000002,ENC000002,DX005,Primary,NaN
2,EDX0000003,ENC000003,DX044,Primary,NaN
3,EDX0000004,ENC000003,DX029,Secondary,NaN
4,EDX0000005,ENC000003,DX047,Secondary,NaN

In [119]:
print(
    "Total encounter diagnosis records:",
    len(encounter_diagnoses_clean_df)
)

print(
    "Average diagnoses per encounter:",
    round(
        len(encounter_diagnoses_clean_df)
        / len(encounters_clean_df),
        2
    )
)

Total encounter diagnosis records: 153136
Average diagnoses per encounter: 1.7

In [120]:
print(
    "Duplicate EncounterDiagnosis IDs:",
    encounter_diagnoses_clean_df[
        "EncounterDiagnosisID"
    ].duplicated().sum()
)

print(
    "Missing EncounterDiagnosis IDs:",
    encounter_diagnoses_clean_df[
        "EncounterDiagnosisID"
    ].isna().sum()
)

Duplicate EncounterDiagnosis IDs: 0
Missing EncounterDiagnosis IDs: 0

In [121]:
invalid_encounter_refs = (
    encounter_diagnoses_clean_df[
        ~encounter_diagnoses_clean_df[
            "EncounterID"
        ].isin(
            encounters_clean_df[
                "EncounterID"
            ]
        )
    ]
)

print(
    "Invalid Encounter references:",
    len(invalid_encounter_refs)
)

Invalid Encounter references: 0

In [122]:
invalid_diagnosis_refs = (
    encounter_diagnoses_clean_df[
        ~encounter_diagnoses_clean_df[
            "DiagnosisID"
        ].isin(
            diagnoses_df[
                "DiagnosisID"
            ]
        )
    ]
)

print(
    "Invalid Diagnosis references:",
    len(invalid_diagnosis_refs)
)

Invalid Diagnosis references: 0

In [123]:
primary_counts = (
    encounter_diagnoses_clean_df[
        encounter_diagnoses_clean_df[
            "DiagnosisType"
        ] == "Primary"
    ]
    .groupby("EncounterID")
    .size()
)

print(
    "Encounters without exactly one primary diagnosis:",
    (primary_counts != 1).sum()
)

Encounters without exactly one primary diagnosis: 0

In [124]:
print(
    "Number of encounters with primary diagnosis:",
    len(primary_counts)
)

Number of encounters with primary diagnosis: 90000

In [125]:
duplicate_pairs = (
    encounter_diagnoses_clean_df
    .duplicated(
        subset=[
            "EncounterID",
            "DiagnosisID"
        ]
    )
    .sum()
)

print(
    "Duplicate Encounter-Diagnosis pairs:",
    duplicate_pairs
)

Duplicate Encounter-Diagnosis pairs: 0

In [126]:
diagnosis_distribution = (
    encounter_diagnoses_clean_df
    .merge(
        diagnoses_df[
            [
                "DiagnosisID",
                "DiagnosisName",
                "DiagnosisCategory",
                "ChronicConditionFlag"
            ]
        ],
        on="DiagnosisID",
        how="left"
    )
)

diagnosis_distribution[
    "DiagnosisCategory"
].value_counts()

DiagnosisCategory
Other                 55688
Respiratory           20481
Heart Disease         14234
Musculoskeletal        9600
Diabetes               8461
Infectious Disease     7556
Mental Health          6535
Hypertension           6138
Asthma                 5175
COPD                   5170
Gastrointestinal       4811
Injury                 3041
Neurological           2996
Cancer                 2152
Kidney Disease         1098
Name: count, dtype: int64

In [127]:
diagnosis_distribution[
    "ChronicConditionFlag"
].value_counts()

ChronicConditionFlag
1    87057
0    66079
Name: count, dtype: int64

In [128]:
diagnosis_age_check = (
    diagnosis_distribution
    .merge(
        encounters_clean_df[
            [
                "EncounterID",
                "PatientID"
            ]
        ],
        on="EncounterID",
        how="left"
    )
)

diagnosis_age_check = (
    diagnosis_age_check
    .merge(
        patients_generation_df[
            [
                "PatientID",
                "ReferenceAge"
            ]
        ],
        on="PatientID",
        how="left"
    )
)

In [129]:
diagnosis_age_check["AgeGroup"] = pd.cut(
    diagnosis_age_check["ReferenceAge"],
    bins=[
        -1,
        17,
        34,
        49,
        64,
        200
    ],
    labels=[
        "0-17",
        "18-34",
        "35-49",
        "50-64",
        "65+"
    ]
)

diagnosis_age_check.groupby(
    "AgeGroup",
    observed=False
)["ChronicConditionFlag"].mean().round(3)

AgeGroup
0-17     0.403
18-34    0.565
35-49    0.561
50-64    0.620
65+      0.610
Name: ChronicConditionFlag, dtype: float64

In [130]:
encounter_diagnoses_df = (
    encounter_diagnoses_clean_df.copy()
)

In [131]:
invalid_diagnosis_count = int(
    len(encounter_diagnoses_df)
    * 0.003
)

print(
    "Diagnosis IDs to corrupt:",
    invalid_diagnosis_count
)

Diagnosis IDs to corrupt: 459

In [132]:
invalid_dx_indices = np.random.choice(
    encounter_diagnoses_df.index,
    size=invalid_diagnosis_count,
    replace=False
)

encounter_diagnoses_df.loc[
    invalid_dx_indices,
    "DiagnosisID"
] = "DX999"

In [133]:
duplicate_pair_count = int(
    len(encounter_diagnoses_clean_df)
    * 0.003
)

duplicate_rows = (
    encounter_diagnoses_clean_df
    .sample(
        n=duplicate_pair_count,
        random_state=2001
    )
    .copy()
)

starting_id = (
    len(encounter_diagnoses_df)
    + 1
)

duplicate_rows[
    "EncounterDiagnosisID"
] = [
    f"EDX{i:07d}"
    for i in range(
        starting_id,
        starting_id
        + len(duplicate_rows)
    )
]

encounter_diagnoses_df = pd.concat(
    [
        encounter_diagnoses_df,
        duplicate_rows
    ],
    ignore_index=True
)

In [134]:
invalid_dx_count_check = (
    ~encounter_diagnoses_df[
        "DiagnosisID"
    ].isin(
        diagnoses_df[
            "DiagnosisID"
        ]
    )
).sum()

duplicate_pair_check = (
    encounter_diagnoses_df
    .duplicated(
        subset=[
            "EncounterID",
            "DiagnosisID"
        ]
    )
    .sum()
)

print(
    "Invalid Diagnosis references:",
    invalid_dx_count_check
)

print(
    "Duplicate Encounter-Diagnosis pairs:",
    duplicate_pair_check
)

Invalid Diagnosis references: 459
Duplicate Encounter-Diagnosis pairs: 459

In [135]:
encounter_diagnoses_df.to_csv(
    RAW_DATA_PATH
    / "encounter_diagnoses.csv",
    index=False
)

print(
    "encounter_diagnoses.csv created successfully."
)

encounter_diagnoses.csv created successfully.

In [136]:
random.seed(3001)
np.random.seed(3001)

print("Encounter procedure generator initialized.")

Encounter procedure generator initialized.

In [137]:
procedure_groups = {
    "laboratory": [
        "PROC001",  # CBC
        "PROC002",  # Basic Metabolic Panel
        "PROC003",  # HbA1c
        "PROC004",  # Lipid Panel
        "PROC005"   # Urinalysis
    ],

    "imaging": [
        "PROC006",  # Chest X-Ray
        "PROC007",  # Abdominal X-Ray
        "PROC008",  # CT Head
        "PROC009",  # CT Chest
        "PROC010",  # MRI Brain
        "PROC011",  # MRI Spine
        "PROC012",  # Ultrasound
        "PROC039",  # Mammography
        "PROC040"   # Bone Density
    ],

    "cardiology": [
        "PROC013",  # ECG
        "PROC014",  # Echocardiogram
        "PROC016",  # Stress Test
        "PROC028"   # Cardiac Catheterization
    ],

    "pulmonary": [
        "PROC006",  # Chest X-Ray
        "PROC009",  # CT Chest
        "PROC015",  # Pulmonary Function
        "PROC020"   # Nebulizer
    ],

    "neurology": [
        "PROC008",  # CT Head
        "PROC010",  # MRI Brain
        "PROC017"   # EEG
    ],

    "orthopedics": [
        "PROC006",
        "PROC007",
        "PROC011",
        "PROC026",  # Knee Arthroscopy
        "PROC027",  # Hip Replacement
        "PROC030"   # Physical Therapy
    ],

    "gastrointestinal": [
        "PROC012",
        "PROC018",  # Endoscopy
        "PROC025",  # Gallbladder Surgery
        "PROC038"   # Colonoscopy
    ],

    "therapeutic": [
        "PROC019",  # IV Fluids
        "PROC020",  # Nebulizer
        "PROC021",  # Wound Care
        "PROC022",  # Medication Infusion
        "PROC023"   # Dialysis
    ],

    "preventive": [
        "PROC033",  # Annual Physical
        "PROC034",  # Vaccination
        "PROC035",  # Cancer Screening
        "PROC036",  # Diabetes Screening
        "PROC037"   # Blood Pressure Screening
    ],

    "rehabilitation": [
        "PROC030",
        "PROC031",
        "PROC032"
    ]
}

In [138]:
def get_procedure_pool(department_name, encounter_type):

    if department_name == "Cardiology":
        return (
            procedure_groups["cardiology"] * 5
            + procedure_groups["laboratory"] * 2
            + procedure_groups["imaging"]
        )

    elif department_name == "Neurology":
        return (
            procedure_groups["neurology"] * 5
            + procedure_groups["laboratory"] * 2
        )

    elif department_name == "Orthopedics":
        return (
            procedure_groups["orthopedics"] * 5
            + procedure_groups["rehabilitation"] * 2
        )

    elif department_name == "Pulmonology":
        return (
            procedure_groups["pulmonary"] * 5
            + procedure_groups["laboratory"] * 2
        )

    elif department_name == "Gastroenterology":
        return (
            procedure_groups["gastrointestinal"] * 5
            + procedure_groups["laboratory"] * 2
        )

    elif department_name == "Endocrinology":
        return (
            ["PROC003", "PROC004", "PROC036", "PROC037"] * 5
            + procedure_groups["laboratory"] * 2
        )

    elif department_name == "Oncology":
        return (
            ["PROC022", "PROC035", "PROC009", "PROC039"] * 4
            + procedure_groups["laboratory"] * 3
        )

    elif department_name == "Emergency Department":
        return (
            procedure_groups["laboratory"] * 3
            + procedure_groups["imaging"] * 3
            + procedure_groups["cardiology"] * 2
            + procedure_groups["therapeutic"] * 3
        )

    elif department_name == "General Medicine":
        return (
            procedure_groups["laboratory"] * 4
            + procedure_groups["therapeutic"] * 2
            + procedure_groups["imaging"]
        )

    elif department_name == "Primary Care":
        return (
            procedure_groups["preventive"] * 4
            + procedure_groups["laboratory"] * 2
        )

    elif department_name == "Pediatrics":
        return (
            ["PROC001", "PROC002", "PROC006",
             "PROC020", "PROC034"] * 4
        )

    elif department_name == "Behavioral Health":
        return [
            "PROC001",
            "PROC002"
        ]

    else:
        return (
            procedure_groups["laboratory"]
            + procedure_groups["imaging"]
            + procedure_groups["preventive"]
        )

In [139]:
procedure_standard_cost = dict(
    zip(
        procedures_df["ProcedureID"],
        procedures_df["StandardCost"]
    )
)

print("Procedure cost lookup created.")

Procedure cost lookup created.

In [140]:
procedure_counts = [0, 1, 2]

procedure_count_probabilities = [
    0.35,
    0.52,
    0.13
]

In [141]:
def generate_actual_procedure_cost(procedure_id):

    standard_cost = procedure_standard_cost[
        procedure_id
    ]

    multiplier = np.random.normal(
        loc=1.00,
        scale=0.08
    )

    actual_cost = (
        standard_cost * multiplier
    )

    return round(
        max(actual_cost, 10),
        2
    )

In [142]:
encounter_procedure_records = []

procedure_counter = 1

for _, encounter in encounters_clean_df.iterrows():

    encounter_id = encounter["EncounterID"]

    department_id = encounter[
        "DepartmentID"
    ]

    encounter_type = encounter[
        "EncounterType"
    ]

    department_name = (
        department_info[
            department_id
        ]["DepartmentName"]
    )

    procedure_count = np.random.choice(
        procedure_counts,
        p=procedure_count_probabilities
    )

    if procedure_count == 0:
        continue

    procedure_pool = get_procedure_pool(
        department_name,
        encounter_type
    )

    selected_procedures = set()

    for _ in range(procedure_count):

        procedure_id = random.choice(
            procedure_pool
        )

        attempts = 0

        while (
            procedure_id in selected_procedures
            and attempts < 10
        ):
            procedure_id = random.choice(
                procedure_pool
            )

            attempts += 1

        if procedure_id in selected_procedures:
            continue

        selected_procedures.add(
            procedure_id
        )

        arrival_datetime = pd.Timestamp(
            encounter["ArrivalDateTime"]
        )

        encounter_end_datetime = pd.Timestamp(
            encounter["EncounterEndDateTime"]
        )

        total_minutes = max(
            int(
                (
                    encounter_end_datetime
                    - arrival_datetime
                ).total_seconds()
                / 60
            ),
            1
        )

        procedure_offset_minutes = random.randint(
            0,
            total_minutes
        )

        procedure_datetime = (
            arrival_datetime
            + timedelta(
                minutes=procedure_offset_minutes
            )
        )

        procedure_date = (
            procedure_datetime.date()
        )

        procedure_cost = (
            generate_actual_procedure_cost(
                procedure_id
            )
        )

        encounter_procedure_records.append(
            (
                f"EPR{procedure_counter:07d}",
                encounter_id,
                procedure_id,
                procedure_date,
                procedure_cost
            )
        )

        procedure_counter += 1

In [143]:
encounter_procedures_clean_df = pd.DataFrame(
    encounter_procedure_records,
    columns=[
        "EncounterProcedureID",
        "EncounterID",
        "ProcedureID",
        "ProcedureDate",
        "ProcedureCost"
    ]
)

encounter_procedures_clean_df.head()

  EncounterProcedureID EncounterID ProcedureID ProcedureDate  ProcedureCost
0           EPR0000001   ENC000003     PROC010    2025-10-02        1585.99
1           EPR0000002   ENC000003     PROC020    2025-10-01         128.26
2           EPR0000003   ENC000005     PROC002    2025-12-16          93.15
3           EPR0000004   ENC000007     PROC037    2024-07-23          43.40
4           EPR0000005   ENC000007     PROC002    2024-07-23          99.74

In [144]:
print(
    "Total procedure records:",
    len(encounter_procedures_clean_df)
)

print(
    "Average procedures per encounter:",
    round(
        len(encounter_procedures_clean_df)
        / len(encounters_clean_df),
        2
    )
)

Total procedure records: 70419
Average procedures per encounter: 0.78

In [145]:
print(
    "Duplicate EncounterProcedure IDs:",
    encounter_procedures_clean_df[
        "EncounterProcedureID"
    ].duplicated().sum()
)

print(
    "Missing EncounterProcedure IDs:",
    encounter_procedures_clean_df[
        "EncounterProcedureID"
    ].isna().sum()
)

Duplicate EncounterProcedure IDs: 0
Missing EncounterProcedure IDs: 0

In [146]:
invalid_encounter_refs = (
    encounter_procedures_clean_df[
        ~encounter_procedures_clean_df[
            "EncounterID"
        ].isin(
            encounters_clean_df[
                "EncounterID"
            ]
        )
    ]
)

print(
    "Invalid Encounter references:",
    len(invalid_encounter_refs)
)

Invalid Encounter references: 0

In [147]:
invalid_procedure_refs = (
    encounter_procedures_clean_df[
        ~encounter_procedures_clean_df[
            "ProcedureID"
        ].isin(
            procedures_df[
                "ProcedureID"
            ]
        )
    ]
)

print(
    "Invalid Procedure references:",
    len(invalid_procedure_refs)
)

Invalid Procedure references: 0

In [148]:
negative_procedure_costs = (
    encounter_procedures_clean_df[
        encounter_procedures_clean_df[
            "ProcedureCost"
        ] < 0
    ]
)

print(
    "Negative Procedure Costs:",
    len(negative_procedure_costs)
)

Negative Procedure Costs: 0

In [149]:
procedure_date_check = (
    encounter_procedures_clean_df
    .merge(
        encounters_clean_df[
            [
                "EncounterID",
                "ArrivalDateTime",
                "EncounterEndDateTime"
            ]
        ],
        on="EncounterID",
        how="left"
    )
)

In [150]:
procedure_date_check[
    "ProcedureDate"
] = pd.to_datetime(
    procedure_date_check[
        "ProcedureDate"
    ]
)

procedure_date_check[
    "ArrivalDateTime"
] = pd.to_datetime(
    procedure_date_check[
        "ArrivalDateTime"
    ]
)

procedure_date_check[
    "EncounterEndDateTime"
] = pd.to_datetime(
    procedure_date_check[
        "EncounterEndDateTime"
    ]
)

In [151]:
invalid_procedure_dates = (
    procedure_date_check[
        (
            procedure_date_check[
                "ProcedureDate"
            ].dt.date
            <
            procedure_date_check[
                "ArrivalDateTime"
            ].dt.date
        )
        |
        (
            procedure_date_check[
                "ProcedureDate"
            ].dt.date
            >
            procedure_date_check[
                "EncounterEndDateTime"
            ].dt.date
        )
    ]
)

print(
    "Procedures outside encounter period:",
    len(invalid_procedure_dates)
)

Procedures outside encounter period: 0

In [152]:
procedure_analysis = (
    encounter_procedures_clean_df
    .merge(
        procedures_df[
            [
                "ProcedureID",
                "ProcedureName",
                "ProcedureCategory",
                "StandardCost"
            ]
        ],
        on="ProcedureID",
        how="left"
    )
)

In [153]:
procedure_analysis[
    "ProcedureCategory"
].value_counts()

ProcedureCategory
Laboratory        27314
Imaging           16652
Therapeutic        8503
Preventive         6948
Diagnostic         6493
Surgical           3180
Rehabilitation     1329
Name: count, dtype: int64

In [154]:
procedure_analysis[
    "ProcedureName"
].value_counts().head(10)

ProcedureName
Basic Metabolic Panel    7130
Complete Blood Count     6932
HbA1c Test               4667
Lipid Panel              4566
Urinalysis               4019
Chest X-Ray              3851
Nebulizer Treatment      3342
CT Scan - Chest          2203
Vaccination              2165
Abdominal X-Ray          1780
Name: count, dtype: int64

In [155]:
procedure_analysis[
    [
        "ProcedureName",
        "StandardCost",
        "ProcedureCost"
    ]
].head(10)

              ProcedureName  StandardCost  ProcedureCost
0               MRI - Brain        1450.0        1585.99
1       Nebulizer Treatment         130.0         128.26
2     Basic Metabolic Panel          95.0          93.15
3  Blood Pressure Screening          45.0          43.40
4     Basic Metabolic Panel          95.0          99.74
5      Complete Blood Count          85.0          75.43
6                Urinalysis          55.0          58.39
7      Complete Blood Count          85.0          87.93
8           CT Scan - Chest         950.0         895.24
9         Bone Density Scan         300.0         273.96

In [156]:
encounter_procedures_df = (
    encounter_procedures_clean_df.copy()
)

In [157]:
invalid_procedure_count = int(
    len(encounter_procedures_df)
    * 0.002
)

print(
    "Procedure IDs to corrupt:",
    invalid_procedure_count
)

Procedure IDs to corrupt: 140

In [158]:
invalid_proc_indices = np.random.choice(
    encounter_procedures_df.index,
    size=invalid_procedure_count,
    replace=False
)

encounter_procedures_df.loc[
    invalid_proc_indices,
    "ProcedureID"
] = "PROC999"

In [159]:
negative_proc_cost_count = int(
    len(encounter_procedures_df)
    * 0.002
)

negative_proc_indices = np.random.choice(
    encounter_procedures_df.index,
    size=negative_proc_cost_count,
    replace=False
)

encounter_procedures_df.loc[
    negative_proc_indices,
    "ProcedureCost"
] = (
    -abs(
        encounter_procedures_df.loc[
            negative_proc_indices,
            "ProcedureCost"
        ]
    )
)

In [160]:
invalid_proc_check = (
    ~encounter_procedures_df[
        "ProcedureID"
    ].isin(
        procedures_df[
            "ProcedureID"
        ]
    )
).sum()

negative_cost_check = (
    encounter_procedures_df[
        "ProcedureCost"
    ] < 0
).sum()

print(
    "Invalid Procedure references:",
    invalid_proc_check
)

print(
    "Negative Procedure Costs:",
    negative_cost_check
)

Invalid Procedure references: 140
Negative Procedure Costs: 140

In [161]:
encounter_procedures_df.to_csv(
    RAW_DATA_PATH
    / "encounter_procedures.csv",
    index=False
)

print(
    "encounter_procedures.csv created successfully."
)

encounter_procedures.csv created successfully.

In [162]:
random.seed(4001)
np.random.seed(4001)

print("Admission generator initialized.")

Admission generator initialized.

In [163]:
inpatient_encounters_df = (
    encounters_clean_df[
        encounters_clean_df["EncounterType"] == "Inpatient"
    ]
    .copy()
)

print(
    "Total inpatient encounters:",
    len(inpatient_encounters_df)
)

Total inpatient encounters: 17740

In [164]:
inpatient_encounters_df[
    [
        "EncounterID",
        "PatientID",
        "DepartmentID",
        "ArrivalDateTime",
        "EncounterEndDateTime"
    ]
].head()

,EncounterID,PatientID,DepartmentID,ArrivalDateTime,EncounterEndDateTime
15,ENC000016,PAT005222,DEP013,2024-08-03 08:14:00,2024-08-07 06:03:56.857084
23,ENC000024,PAT001049,DEP002,2024-10-27 21:25:00,2024-11-03 17:05:12.067328
25,ENC000026,PAT004167,DEP002,2025-02-26 10:32:00,2025-03-05 05:48:53.130791
38,ENC000039,PAT006068,DEP002,2025-12-26 09:16:00,2025-12-28 22:47:58.253861
39,ENC000040,PAT001095,DEP013,2025-09-27 20:01:00,2025-10-04 05:23:25.600755

In [165]:
admission_types = [
    "Emergency",
    "Elective",
    "Urgent"
]

admission_type_probabilities = [
    0.55,
    0.20,
    0.25
]

In [166]:
def choose_discharge_disposition(age):

    if age >= 65:

        dispositions = [
            "Home",
            "Home with Services",
            "Skilled Nursing Facility",
            "Rehabilitation Facility",
            "Transfer to Another Facility",
            "Left Against Medical Advice",
            "Expired",
            "Other"
        ]

        probabilities = [
            0.48,
            0.18,
            0.12,
            0.08,
            0.05,
            0.02,
            0.02,
            0.05
        ]

    else:

        dispositions = [
            "Home",
            "Home with Services",
            "Skilled Nursing Facility",
            "Rehabilitation Facility",
            "Transfer to Another Facility",
            "Left Against Medical Advice",
            "Expired",
            "Other"
        ]

        probabilities = [
            0.70,
            0.10,
            0.04,
            0.04,
            0.04,
            0.03,
            0.01,
            0.04
        ]

    return np.random.choice(
        dispositions,
        p=probabilities
    )

In [167]:
primary_diagnoses_df = (
    encounter_diagnoses_clean_df[
        encounter_diagnoses_clean_df[
            "DiagnosisType"
        ] == "Primary"
    ]
    [
        [
            "EncounterID",
            "DiagnosisID"
        ]
    ]
    .copy()
)

primary_diagnoses_df = (
    primary_diagnoses_df
    .merge(
        diagnoses_df[
            [
                "DiagnosisID",
                "ChronicConditionFlag"
            ]
        ],
        on="DiagnosisID",
        how="left"
    )
)

primary_chronic_lookup = dict(
    zip(
        primary_diagnoses_df["EncounterID"],
        primary_diagnoses_df[
            "ChronicConditionFlag"
        ]
    )
)

print("Primary diagnosis lookup created.")

Primary diagnosis lookup created.

In [168]:
admission_records = []

for i, (_, encounter) in enumerate(
    inpatient_encounters_df.iterrows(),
    start=1
):

    admission_id = f"ADM{i:06d}"

    encounter_id = encounter["EncounterID"]
    patient_id = encounter["PatientID"]
    department_id = encounter["DepartmentID"]

    patient_age = patient_age_lookup[
        patient_id
    ]

    admission_datetime = pd.Timestamp(
        encounter["ArrivalDateTime"]
    )

    discharge_datetime = pd.Timestamp(
        encounter["EncounterEndDateTime"]
    )

    admission_type = np.random.choice(
        admission_types,
        p=admission_type_probabilities
    )

    discharge_disposition = (
        choose_discharge_disposition(
            patient_age
        )
    )

    chronic_flag = (
        primary_chronic_lookup.get(
            encounter_id,
            0
        )
    )

    # ---------------------------------
    # Follow-up requirement
    # ---------------------------------

    if (
        chronic_flag == 1
        or patient_age >= 65
    ):
        follow_up_required_probability = 0.85
    else:
        follow_up_required_probability = 0.65

    follow_up_required = (
        1
        if random.random()
        < follow_up_required_probability
        else 0
    )

    # ---------------------------------
    # Follow-up completion
    # ---------------------------------

    if follow_up_required == 1:

        discharge_year = (
            discharge_datetime.year
        )

        # Slightly declining follow-up
        # performance over time
        if discharge_year == 2023:
            completion_probability = 0.78

        elif discharge_year == 2024:
            completion_probability = 0.72

        else:
            completion_probability = 0.66

        follow_up_completed = (
            1
            if random.random()
            < completion_probability
            else 0
        )

    else:
        follow_up_completed = 0

    # ---------------------------------
    # Follow-up date
    # ---------------------------------

    if follow_up_completed == 1:

        days_to_follow_up = int(
            np.random.choice(
                [
                    3,
                    5,
                    7,
                    10,
                    14,
                    21,
                    30
                ],
                p=[
                    0.08,
                    0.12,
                    0.25,
                    0.18,
                    0.20,
                    0.10,
                    0.07
                ]
            )
        )

        follow_up_date = (
            discharge_datetime
            + timedelta(
                days=days_to_follow_up
            )
        ).date()

    else:
        follow_up_date = None

    admission_records.append(
        (
            admission_id,
            encounter_id,
            patient_id,
            department_id,
            admission_datetime,
            discharge_datetime,
            admission_type,
            discharge_disposition,
            follow_up_required,
            follow_up_completed,
            follow_up_date
        )
    )

In [169]:
admissions_clean_df = pd.DataFrame(
    admission_records,
    columns=[
        "AdmissionID",
        "EncounterID",
        "PatientID",
        "DepartmentID",
        "AdmissionDateTime",
        "DischargeDateTime",
        "AdmissionType",
        "DischargeDisposition",
        "FollowUpRequiredFlag",
        "FollowUpCompletedFlag",
        "FollowUpDate"
    ]
)

admissions_clean_df.head()

,AdmissionID,EncounterID,PatientID,DepartmentID,AdmissionDateTime,DischargeDateTime,AdmissionType,DischargeDisposition,FollowUpRequiredFlag,FollowUpCompletedFlag,FollowUpDate
0,ADM000001,ENC000016,PAT005222,DEP013,2024-08-03 08:14:00,2024-08-07 06:03:56.857084,Emergency,Skilled Nursing Facility,1,1,2024-09-06
1,ADM000002,ENC000024,PAT001049,DEP002,2024-10-27 21:25:00,2024-11-03 17:05:12.067328,Emergency,Home,1,0,None
2,ADM000003,ENC000026,PAT004167,DEP002,2025-02-26 10:32:00,2025-03-05 05:48:53.130791,Elective,Home,1,0,None
3,ADM000004,ENC000039,PAT006068,DEP002,2025-12-26 09:16:00,2025-12-28 22:47:58.253861,Elective,Home,1,1,2026-01-04
4,ADM000005,ENC000040,PAT001095,DEP013,2025-09-27 20:01:00,2025-10-04 05:23:25.600755,Emergency,Home,1,0,None

In [170]:
print(
    "Total admissions:",
    len(admissions_clean_df)
)

print(
    "Total inpatient encounters:",
    len(inpatient_encounters_df)
)

Total admissions: 17740
Total inpatient encounters: 17740

In [171]:
print(
    "Duplicate Admission IDs:",
    admissions_clean_df[
        "AdmissionID"
    ].duplicated().sum()
)

print(
    "Missing Admission IDs:",
    admissions_clean_df[
        "AdmissionID"
    ].isna().sum()
)

Duplicate Admission IDs: 0
Missing Admission IDs: 0

In [172]:
invalid_encounter_refs = admissions_clean_df[
    ~admissions_clean_df[
        "EncounterID"
    ].isin(
        encounters_clean_df[
            "EncounterID"
        ]
    )
]

invalid_patient_refs = admissions_clean_df[
    ~admissions_clean_df[
        "PatientID"
    ].isin(
        patients_clean_df[
            "PatientID"
        ]
    )
]

invalid_department_refs = admissions_clean_df[
    ~admissions_clean_df[
        "DepartmentID"
    ].isin(
        departments_df[
            "DepartmentID"
        ]
    )
]

print(
    "Invalid Encounter references:",
    len(invalid_encounter_refs)
)

print(
    "Invalid Patient references:",
    len(invalid_patient_refs)
)

print(
    "Invalid Department references:",
    len(invalid_department_refs)
)

Invalid Encounter references: 0
Invalid Patient references: 0
Invalid Department references: 0

In [173]:
admission_patient_check = (
    admissions_clean_df
    .merge(
        encounters_clean_df[
            [
                "EncounterID",
                "PatientID"
            ]
        ],
        on="EncounterID",
        how="left",
        suffixes=(
            "_Admission",
            "_Encounter"
        )
    )
)

patient_mismatches = admission_patient_check[
    admission_patient_check[
        "PatientID_Admission"
    ]
    !=
    admission_patient_check[
        "PatientID_Encounter"
    ]
]

print(
    "Admission / Encounter Patient mismatches:",
    len(patient_mismatches)
)

Admission / Encounter Patient mismatches: 0

In [174]:
invalid_stays = admissions_clean_df[
    admissions_clean_df[
        "DischargeDateTime"
    ]
    <
    admissions_clean_df[
        "AdmissionDateTime"
    ]
]

print(
    "Discharge before Admission:",
    len(invalid_stays)
)

Discharge before Admission: 0

In [175]:
los_check_df = admissions_clean_df.copy()

los_check_df["LengthOfStayDays"] = (
    (
        pd.to_datetime(
            los_check_df[
                "DischargeDateTime"
            ]
        )
        -
        pd.to_datetime(
            los_check_df[
                "AdmissionDateTime"
            ]
        )
    )
    .dt.total_seconds()
    / 86400
)

los_check_df[
    "LengthOfStayDays"
].describe()

count    17740.000000
mean         4.012544
std          1.737284
min          1.007055
25%          2.495256
50%          4.003667
75%          5.511799
max          7.121890
Name: LengthOfStayDays, dtype: float64

In [176]:
invalid_followup_logic = admissions_clean_df[
    (
        admissions_clean_df[
            "FollowUpCompletedFlag"
        ] == 1
    )
    &
    (
        admissions_clean_df[
            "FollowUpRequiredFlag"
        ] == 0
    )
]

print(
    "Completed follow-up without requirement:",
    len(invalid_followup_logic)
)

Completed follow-up without requirement: 0

In [177]:
missing_completed_followup_dates = (
    admissions_clean_df[
        (
            admissions_clean_df[
                "FollowUpCompletedFlag"
            ] == 1
        )
        &
        (
            admissions_clean_df[
                "FollowUpDate"
            ].isna()
        )
    ]
)

print(
    "Completed follow-ups missing date:",
    len(
        missing_completed_followup_dates
    )
)

Completed follow-ups missing date: 0

In [178]:
readmission_check_df = (
    admissions_clean_df[
        admissions_clean_df[
            "DischargeDisposition"
        ] != "Expired"
    ]
    .copy()
)

readmission_check_df = (
    readmission_check_df
    .sort_values(
        [
            "PatientID",
            "AdmissionDateTime"
        ]
    )
)

readmission_check_df[
    "NextAdmissionDateTime"
] = (
    readmission_check_df
    .groupby(
        "PatientID"
    )[
        "AdmissionDateTime"
    ]
    .shift(-1)
)

readmission_check_df[
    "DaysToNextAdmission"
] = (
    (
        readmission_check_df[
            "NextAdmissionDateTime"
        ]
        -
        readmission_check_df[
            "DischargeDateTime"
        ]
    )
    .dt.total_seconds()
    / 86400
)

readmission_check_df[
    "Potential30DayReadmission"
] = (
    readmission_check_df[
        "DaysToNextAdmission"
    ]
    .between(
        0,
        30,
        inclusive="both"
    )
)

temporary_readmission_rate = (
    readmission_check_df[
        "Potential30DayReadmission"
    ].mean()
    * 100
)

print(
    "Temporary 30-day readmission check:",
    round(
        temporary_readmission_rate,
        2
    ),
    "%"
)

Temporary 30-day readmission check: 13.53 %

In [179]:
followup_check_df = (
    admissions_clean_df[
        admissions_clean_df[
            "FollowUpRequiredFlag"
        ] == 1
    ]
    .copy()
)

followup_check_df[
    "DischargeYear"
] = pd.to_datetime(
    followup_check_df[
        "DischargeDateTime"
    ]
).dt.year

(
    followup_check_df
    .groupby(
        "DischargeYear"
    )[
        "FollowUpCompletedFlag"
    ]
    .mean()
    .mul(100)
    .round(1)
)

DischargeYear
2023    78.2
2024    72.0
2025    65.4
2026    71.5
Name: FollowUpCompletedFlag, dtype: float64

In [180]:
admissions_df = (
    admissions_clean_df.copy()
)

In [181]:
bad_discharge_count = max(
    1,
    int(
        len(admissions_df)
        * 0.003
    )
)

bad_discharge_indices = (
    np.random.choice(
        admissions_df.index,
        size=bad_discharge_count,
        replace=False
    )
)

admissions_df.loc[
    bad_discharge_indices,
    "DischargeDateTime"
] = (
    pd.to_datetime(
        admissions_df.loc[
            bad_discharge_indices,
            "AdmissionDateTime"
        ]
    )
    -
    pd.to_timedelta(
        np.random.randint(
            1,
            49,
            size=bad_discharge_count
        ),
        unit="h"
    )
)

In [182]:
missing_discharge_count = max(
    1,
    int(
        len(admissions_df)
        * 0.007
    )
)

available_indices = admissions_df.index.difference(
    bad_discharge_indices
)

missing_discharge_indices = (
    np.random.choice(
        available_indices,
        size=missing_discharge_count,
        replace=False
    )
)

admissions_df.loc[
    missing_discharge_indices,
    "DischargeDateTime"
] = pd.NaT

In [183]:
completed_followups = admissions_df[
    admissions_df[
        "FollowUpCompletedFlag"
    ] == 1
].index

missing_followup_count = min(
    len(completed_followups),
    max(
        1,
        int(
            len(admissions_df)
            * 0.005
        )
    )
)

missing_followup_indices = (
    np.random.choice(
        completed_followups,
        size=missing_followup_count,
        replace=False
    )
)

admissions_df.loc[
    missing_followup_indices,
    "FollowUpDate"
] = None

In [184]:
bad_discharge_check = (
    (
        pd.to_datetime(
            admissions_df[
                "DischargeDateTime"
            ]
        )
        <
        pd.to_datetime(
            admissions_df[
                "AdmissionDateTime"
            ]
        )
    )
    .sum()
)

missing_discharge_check = (
    admissions_df[
        "DischargeDateTime"
    ]
    .isna()
    .sum()
)

missing_followup_date_check = (
    (
        admissions_df[
            "FollowUpCompletedFlag"
        ] == 1
    )
    &
    (
        admissions_df[
            "FollowUpDate"
        ].isna()
    )
).sum()

print(
    "Discharge before Admission:",
    bad_discharge_check
)

print(
    "Missing DischargeDateTime:",
    missing_discharge_check
)

print(
    "Completed follow-ups missing FollowUpDate:",
    missing_followup_date_check
)

Discharge before Admission: 53
Missing DischargeDateTime: 124
Completed follow-ups missing FollowUpDate: 88

In [185]:
admissions_df.to_csv(
    RAW_DATA_PATH / "admissions.csv",
    index=False
)

print(
    "admissions.csv created successfully."
)

admissions.csv created successfully.

In [186]:
random.seed(5001)
np.random.seed(5001)

appointment_count = 50_000

print("Appointment generator initialized.")

Appointment generator initialized.

In [187]:
providers_by_department = (
    providers_df
    .groupby("DepartmentID")["ProviderID"]
    .apply(list)
    .to_dict()
)

print("Provider lookup ready.")

Provider lookup ready.

In [188]:
appointment_departments_df = departments_df[
    departments_df["DepartmentType"].isin(
        [
            "Specialty",
            "Primary Care",
            "Outpatient",
            "Behavioral Health"
        ]
    )
].copy()

appointment_department_ids = (
    appointment_departments_df["DepartmentID"]
    .tolist()
)

print(
    "Departments available for appointments:",
    len(appointment_department_ids)
)

Departments available for appointments: 19

In [189]:
appointment_types = [
    "New Patient",
    "Follow-Up",
    "Routine",
    "Specialist",
    "Post-Discharge Follow-Up"
]

appointment_type_probabilities = [
    0.15,
    0.30,
    0.25,
    0.20,
    0.10
]

In [190]:
def generate_booking_lead_days(appointment_type):

    if appointment_type == "Post-Discharge Follow-Up":
        return random.randint(1, 14)

    elif appointment_type == "Follow-Up":
        return random.randint(3, 45)

    elif appointment_type == "New Patient":
        return random.randint(5, 60)

    elif appointment_type == "Specialist":
        return random.randint(7, 75)

    else:
        return random.randint(1, 40)

In [191]:
def choose_appointment_status(
    booking_lead_days,
    appointment_type
):

    no_show_prob = 0.08
    cancelled_prob = 0.10
    rescheduled_prob = 0.06

    if booking_lead_days > 30:
        no_show_prob += 0.05

    if booking_lead_days > 60:
        no_show_prob += 0.04

    if appointment_type == "Post-Discharge Follow-Up":
        no_show_prob -= 0.02

    no_show_prob = max(no_show_prob, 0.02)

    completed_prob = (
        1
        - no_show_prob
        - cancelled_prob
        - rescheduled_prob
    )

    return np.random.choice(
        [
            "Completed",
            "Cancelled",
            "No Show",
            "Rescheduled"
        ],
        p=[
            completed_prob,
            cancelled_prob,
            no_show_prob,
            rescheduled_prob
        ]
    )

In [192]:
cancellation_reasons = [
    "Patient Request",
    "Provider Unavailable",
    "Scheduling Conflict",
    "Insurance Issue",
    "Transportation Issue",
    "Other"
]

In [193]:
appointment_records = []

for i in range(appointment_count):

    appointment_id = f"APT{i + 1:06d}"

    # -------------------------
    # Patient
    # -------------------------

    patient_index = np.random.choice(
        patients_generation_df.index,
        p=patient_probabilities
    )

    patient_row = patients_generation_df.loc[
        patient_index
    ]

    patient_id = patient_row["PatientID"]

    registration_date = (
        patient_row["RegistrationDate"].date()
    )

    # -------------------------
    # Department
    # -------------------------

    department_id = random.choice(
        appointment_department_ids
    )

    # -------------------------
    # Provider
    # -------------------------

    provider_id = random.choice(
        providers_by_department[
            department_id
        ]
    )

    # -------------------------
    # Appointment Type
    # -------------------------

    appointment_type = np.random.choice(
        appointment_types,
        p=appointment_type_probabilities
    )

    # -------------------------
    # Scheduled Date
    # -------------------------

    latest_schedule_date = datetime(
        2025,
        11,
        30
    ).date()

    days_available = (
        latest_schedule_date
        - registration_date
    ).days

    scheduled_date = (
        registration_date
        + timedelta(
            days=random.randint(
                0,
                max(days_available, 0)
            )
        )
    )

    # -------------------------
    # Booking Lead Time
    # -------------------------

    booking_lead_days = (
        generate_booking_lead_days(
            appointment_type
        )
    )

    appointment_date = (
        scheduled_date
        + timedelta(
            days=booking_lead_days
        )
    )

    # Keep inside study period
    if appointment_date > datetime(
        2025,
        12,
        31
    ).date():

        appointment_date = datetime(
            2025,
            12,
            31
        ).date()

    # -------------------------
    # Appointment Time
    # -------------------------

    appointment_hour = random.randint(
        8,
        16
    )

    appointment_minute = random.choice(
        [0, 15, 30, 45]
    )

    appointment_datetime = datetime.combine(
        appointment_date,
        datetime.min.time()
    ).replace(
        hour=appointment_hour,
        minute=appointment_minute
    )

    # -------------------------
    # Status
    # -------------------------

    actual_lead_days = (
        appointment_date
        - scheduled_date
    ).days

    appointment_status = (
        choose_appointment_status(
            actual_lead_days,
            appointment_type
        )
    )

    # -------------------------
    # Cancellation Reason
    # -------------------------

    if appointment_status == "Cancelled":
        cancellation_reason = random.choice(
            cancellation_reasons
        )
    else:
        cancellation_reason = None

    appointment_records.append(
        (
            appointment_id,
            patient_id,
            provider_id,
            department_id,
            scheduled_date,
            appointment_datetime,
            appointment_status,
            appointment_type,
            cancellation_reason
        )
    )

In [194]:
appointments_clean_df = pd.DataFrame(
    appointment_records,
    columns=[
        "AppointmentID",
        "PatientID",
        "ProviderID",
        "DepartmentID",
        "ScheduledDate",
        "AppointmentDateTime",
        "AppointmentStatus",
        "AppointmentType",
        "CancellationReason"
    ]
)

appointments_clean_df.head()

,AppointmentID,PatientID,ProviderID,DepartmentID,ScheduledDate,AppointmentDateTime,AppointmentStatus,AppointmentType,CancellationReason
0,APT000001,PAT001942,PRV023,DEP025,2025-11-11,2025-11-23 16:00:00,Completed,Post-Discharge Follow-Up,NaN
1,APT000002,PAT009810,PRV074,DEP004,2025-08-15,2025-08-29 16:45:00,Completed,Routine,NaN
2,APT000003,PAT008784,PRV057,DEP021,2025-04-15,2025-06-10 14:00:00,Completed,Specialist,NaN
3,APT000004,PAT004494,PRV106,DEP019,2024-09-03,2024-11-01 16:15:00,Cancelled,Specialist,Scheduling Conflict
4,APT000005,PAT009138,PRV116,DEP009,2025-06-01,2025-06-04 13:45:00,Completed,Follow-Up,NaN

In [195]:
print(
    "Total appointments:",
    len(appointments_clean_df)
)

print(
    "Total columns:",
    len(appointments_clean_df.columns)
)

Total appointments: 50000
Total columns: 9

In [196]:
print(
    "Duplicate Appointment IDs:",
    appointments_clean_df[
        "AppointmentID"
    ].duplicated().sum()
)

print(
    "Missing Appointment IDs:",
    appointments_clean_df[
        "AppointmentID"
    ].isna().sum()
)

Duplicate Appointment IDs: 0
Missing Appointment IDs: 0

In [197]:
invalid_patient_refs = appointments_clean_df[
    ~appointments_clean_df[
        "PatientID"
    ].isin(
        patients_clean_df[
            "PatientID"
        ]
    )
]

invalid_department_refs = appointments_clean_df[
    ~appointments_clean_df[
        "DepartmentID"
    ].isin(
        departments_df[
            "DepartmentID"
        ]
    )
]

invalid_provider_refs = appointments_clean_df[
    ~appointments_clean_df[
        "ProviderID"
    ].isin(
        providers_df[
            "ProviderID"
        ]
    )
]

print(
    "Invalid Patient references:",
    len(invalid_patient_refs)
)

print(
    "Invalid Department references:",
    len(invalid_department_refs)
)

print(
    "Invalid Provider references:",
    len(invalid_provider_refs)
)

Invalid Patient references: 0
Invalid Department references: 0
Invalid Provider references: 0

In [198]:
appointment_provider_check = (
    appointments_clean_df
    .merge(
        providers_df[
            [
                "ProviderID",
                "DepartmentID"
            ]
        ],
        on="ProviderID",
        how="left",
        suffixes=(
            "_Appointment",
            "_Provider"
        )
    )
)

provider_department_mismatches = (
    appointment_provider_check[
        appointment_provider_check[
            "DepartmentID_Appointment"
        ]
        !=
        appointment_provider_check[
            "DepartmentID_Provider"
        ]
    ]
)

print(
    "Provider / Department mismatches:",
    len(provider_department_mismatches)
)

Provider / Department mismatches: 0

In [199]:
invalid_appointment_dates = (
    appointments_clean_df[
        pd.to_datetime(
            appointments_clean_df[
                "AppointmentDateTime"
            ]
        ).dt.date
        <
        pd.to_datetime(
            appointments_clean_df[
                "ScheduledDate"
            ]
        ).dt.date
    ]
)

print(
    "Appointment before ScheduledDate:",
    len(invalid_appointment_dates)
)

Appointment before ScheduledDate: 0

In [200]:
cancelled_missing_reason = (
    appointments_clean_df[
        (
            appointments_clean_df[
                "AppointmentStatus"
            ] == "Cancelled"
        )
        &
        (
            appointments_clean_df[
                "CancellationReason"
            ].isna()
        )
    ]
)

print(
    "Cancelled appointments missing reason:",
    len(cancelled_missing_reason)
)

Cancelled appointments missing reason: 0

In [201]:
non_cancelled_with_reason = (
    appointments_clean_df[
        (
            appointments_clean_df[
                "AppointmentStatus"
            ] != "Cancelled"
        )
        &
        (
            appointments_clean_df[
                "CancellationReason"
            ].notna()
        )
    ]
)

print(
    "Non-cancelled appointments with cancellation reason:",
    len(non_cancelled_with_reason)
)

Non-cancelled appointments with cancellation reason: 0

In [202]:
appointments_clean_df[
    "AppointmentStatus"
].value_counts()

AppointmentStatus
Completed      37138
Cancelled       4997
No Show         4871
Rescheduled     2994
Name: count, dtype: int64

In [203]:
(
    appointments_clean_df[
        "AppointmentStatus"
    ]
    .value_counts(
        normalize=True
    )
    .mul(100)
    .round(2)
)

AppointmentStatus
Completed      74.28
Cancelled       9.99
No Show         9.74
Rescheduled     5.99
Name: proportion, dtype: float64

In [204]:
appointment_check_df = (
    appointments_clean_df.copy()
)

appointment_check_df[
    "BookingLeadDays"
] = (
    pd.to_datetime(
        appointment_check_df[
            "AppointmentDateTime"
        ]
    ).dt.normalize()
    -
    pd.to_datetime(
        appointment_check_df[
            "ScheduledDate"
        ]
    )
).dt.days

In [205]:
appointment_check_df[
    "BookingLeadDays"
].describe()

count    50000.000000
mean        25.541220
std         16.788117
min          0.000000
25%         12.000000
50%         23.000000
75%         37.000000
max         75.000000
Name: BookingLeadDays, dtype: float64

In [206]:
appointment_check_df[
    "LeadTimeGroup"
] = pd.cut(
    appointment_check_df[
        "BookingLeadDays"
    ],
    bins=[
        -1,
        7,
        30,
        60,
        999
    ],
    labels=[
        "0-7 Days",
        "8-30 Days",
        "31-60 Days",
        "61+ Days"
    ]
)

appointment_check_df[
    "NoShowFlag"
] = (
    appointment_check_df[
        "AppointmentStatus"
    ] == "No Show"
).astype(int)

In [207]:
(
    appointment_check_df
    .groupby(
        "LeadTimeGroup",
        observed=False
    )["NoShowFlag"]
    .mean()
    .mul(100)
    .round(2)
)

LeadTimeGroup
0-7 Days       7.29
8-30 Days      7.76
31-60 Days    12.85
61+ Days      17.22
Name: NoShowFlag, dtype: float64

In [208]:
appointments_df = (
    appointments_clean_df.copy()
)

In [209]:
invalid_status_count = int(
    len(appointments_df)
    * 0.003
)

invalid_status_indices = (
    np.random.choice(
        appointments_df.index,
        size=invalid_status_count,
        replace=False
    )
)

bad_status_values = [
    "NO_SHOW",
    "Complete",
    "Canceled",
    "UnknownStatus"
]

appointments_df.loc[
    invalid_status_indices,
    "AppointmentStatus"
] = np.random.choice(
    bad_status_values,
    size=invalid_status_count
)

In [210]:
bad_date_count = int(
    len(appointments_df)
    * 0.004
)

available_indices = (
    appointments_df.index.difference(
        invalid_status_indices
    )
)

bad_date_indices = np.random.choice(
    available_indices,
    size=bad_date_count,
    replace=False
)

appointments_df.loc[
    bad_date_indices,
    "AppointmentDateTime"
] = (
    pd.to_datetime(
        appointments_df.loc[
            bad_date_indices,
            "ScheduledDate"
        ]
    )
    -
    pd.to_timedelta(
        np.random.randint(
            1,
            15,
            size=bad_date_count
        ),
        unit="D"
    )
)

In [211]:
missing_provider_count = int(
    len(appointments_df)
    * 0.008
)

missing_provider_indices = np.random.choice(
    appointments_df.index,
    size=missing_provider_count,
    replace=False
)

appointments_df.loc[
    missing_provider_indices,
    "ProviderID"
] = np.nan

In [212]:
approved_appointment_statuses = [
    "Completed",
    "Cancelled",
    "No Show",
    "Rescheduled"
]

invalid_status_check = (
    ~appointments_df[
        "AppointmentStatus"
    ].isin(
        approved_appointment_statuses
    )
).sum()

bad_date_check = (
    pd.to_datetime(
        appointments_df[
            "AppointmentDateTime"
        ]
    ).dt.date
    <
    pd.to_datetime(
        appointments_df[
            "ScheduledDate"
        ]
    ).dt.date
).sum()

missing_provider_check = (
    appointments_df[
        "ProviderID"
    ].isna().sum()
)

print(
    "Invalid AppointmentStatus values:",
    invalid_status_check
)

print(
    "Appointment before ScheduledDate:",
    bad_date_check
)

print(
    "Missing ProviderID:",
    missing_provider_check
)

Invalid AppointmentStatus values: 150
Appointment before ScheduledDate: 200
Missing ProviderID: 400

In [213]:
appointments_df.to_csv(
    RAW_DATA_PATH
    / "appointments.csv",
    index=False
)

print(
    "appointments.csv created successfully."
)

appointments.csv created successfully.

In [214]:
random.seed(6001)
np.random.seed(6001)

print("Lab results generator initialized.")

Lab results generator initialized.

In [215]:
lab_test_config = {
    "HbA1c": {
        "unit": "%",
        "low": 4.0,
        "high": 5.6,
        "mean": 6.2,
        "std": 1.3
    },

    "Glucose": {
        "unit": "mg/dL",
        "low": 70,
        "high": 99,
        "mean": 105,
        "std": 30
    },

    "LDL Cholesterol": {
        "unit": "mg/dL",
        "low": 0,
        "high": 100,
        "mean": 115,
        "std": 35
    },

    "Creatinine": {
        "unit": "mg/dL",
        "low": 0.6,
        "high": 1.3,
        "mean": 1.0,
        "std": 0.3
    },

    "Hemoglobin": {
        "unit": "g/dL",
        "low": 12.0,
        "high": 17.5,
        "mean": 14.2,
        "std": 1.8
    }
}

In [216]:
def classify_lab_result(value, low, high):

    if value < low:
        return "Low"

    elif value > high * 1.5:
        return "Critical"

    elif value > high:
        return "High"

    else:
        return "Normal"

In [217]:
lab_result_records = []

lab_counter = 1

eligible_encounters = encounters_clean_df[
    encounters_clean_df["EncounterStatus"] != "Left Without Being Seen"
].copy()

while len(lab_result_records) < 100_000:

    encounter = eligible_encounters.sample(1).iloc[0]

    encounter_id = encounter["EncounterID"]
    patient_id = encounter["PatientID"]

    lab_test = random.choice(
        list(lab_test_config.keys())
    )

    config = lab_test_config[lab_test]

    result_value = np.random.normal(
        config["mean"],
        config["std"]
    )

    result_value = round(
        max(result_value, 0.01),
        2
    )

    reference_low = config["low"]
    reference_high = config["high"]

    result_flag = classify_lab_result(
        result_value,
        reference_low,
        reference_high
    )

    arrival = pd.Timestamp(
        encounter["ArrivalDateTime"]
    )

    encounter_end = pd.Timestamp(
        encounter["EncounterEndDateTime"]
    )

    total_minutes = max(
        int(
            (encounter_end - arrival)
            .total_seconds() / 60
        ),
        1
    )

    result_datetime = (
        arrival
        + timedelta(
            minutes=random.randint(
                0,
                total_minutes
            )
        )
    )

    lab_result_records.append(
        (
            f"LAB{lab_counter:07d}",
            encounter_id,
            patient_id,
            lab_test,
            result_value,
            config["unit"],
            reference_low,
            reference_high,
            result_flag,
            result_datetime
        )
    )

    lab_counter += 1

In [218]:
lab_results_clean_df = pd.DataFrame(
    lab_result_records,
    columns=[
        "LabResultID",
        "EncounterID",
        "PatientID",
        "LabTest",
        "ResultValue",
        "ResultUnit",
        "ReferenceLow",
        "ReferenceHigh",
        "ResultFlag",
        "ResultDateTime"
    ]
)

lab_results_clean_df.head()

,LabResultID,EncounterID,PatientID,LabTest,ResultValue,ResultUnit,ReferenceLow,ReferenceHigh,ResultFlag,ResultDateTime
0,LAB0000001,ENC029144,PAT000376,LDL Cholesterol,137.56,mg/dL,0.0,100.0,High,2024-09-04 16:23:00
1,LAB0000002,ENC072776,PAT003049,Glucose,95.48,mg/dL,70.0,99.0,Normal,2024-02-28 09:47:00
2,LAB0000003,ENC006581,PAT009138,Hemoglobin,14.46,g/dL,12.0,17.5,Normal,2024-03-11 08:04:00
3,LAB0000004,ENC089691,PAT002228,Glucose,85.53,mg/dL,70.0,99.0,Normal,2025-08-01 10:18:00
4,LAB0000005,ENC015337,PAT008820,LDL Cholesterol,115.83,mg/dL,0.0,100.0,High,2025-10-12 14:09:00

In [219]:
print("Total lab results:", len(lab_results_clean_df))

print(
    "Duplicate LabResult IDs:",
    lab_results_clean_df["LabResultID"]
    .duplicated()
    .sum()
)

print(
    "Invalid Encounter references:",
    (
        ~lab_results_clean_df["EncounterID"]
        .isin(encounters_clean_df["EncounterID"])
    ).sum()
)

print(
    "Invalid Patient references:",
    (
        ~lab_results_clean_df["PatientID"]
        .isin(patients_clean_df["PatientID"])
    ).sum()
)

Total lab results: 100000
Duplicate LabResult IDs: 0
Invalid Encounter references: 0
Invalid Patient references: 0

In [220]:
lab_results_df = lab_results_clean_df.copy()

In [221]:
missing_unit_count = int(
    len(lab_results_df) * 0.007
)

missing_unit_indices = np.random.choice(
    lab_results_df.index,
    size=missing_unit_count,
    replace=False
)

lab_results_df.loc[
    missing_unit_indices,
    "ResultUnit"
] = np.nan

In [222]:
invalid_unit_count = int(
    len(lab_results_df) * 0.003
)

available_indices = lab_results_df.index.difference(
    missing_unit_indices
)

invalid_unit_indices = np.random.choice(
    available_indices,
    size=invalid_unit_count,
    replace=False
)

lab_results_df.loc[
    invalid_unit_indices,
    "ResultUnit"
] = "INVALID_UNIT"

In [223]:
outlier_count = int(
    len(lab_results_df) * 0.003
)

outlier_indices = np.random.choice(
    lab_results_df.index,
    size=outlier_count,
    replace=False
)

lab_results_df.loc[
    outlier_indices,
    "ResultValue"
] = (
    lab_results_df.loc[
        outlier_indices,
        "ResultValue"
    ] * 50
)

In [224]:
bad_range_count = int(
    len(lab_results_df) * 0.002
)

bad_range_indices = np.random.choice(
    lab_results_df.index,
    size=bad_range_count,
    replace=False
)

temp_low = lab_results_df.loc[
    bad_range_indices,
    "ReferenceLow"
].copy()

lab_results_df.loc[
    bad_range_indices,
    "ReferenceLow"
] = (
    lab_results_df.loc[
        bad_range_indices,
        "ReferenceHigh"
    ] + 10
)

In [225]:
print(
    "Missing ResultUnit:",
    lab_results_df["ResultUnit"].isna().sum()
)

print(
    "Invalid units:",
    (
        lab_results_df["ResultUnit"]
        == "INVALID_UNIT"
    ).sum()
)

print(
    "ReferenceLow > ReferenceHigh:",
    (
        lab_results_df["ReferenceLow"]
        >
        lab_results_df["ReferenceHigh"]
    ).sum()
)

Missing ResultUnit: 700
Invalid units: 300
ReferenceLow > ReferenceHigh: 200

In [226]:
lab_results_df.to_csv(
    RAW_DATA_PATH / "lab_results.csv",
    index=False
)

print("lab_results.csv created successfully.")

lab_results.csv created successfully.